src/objects/ACCOUNT_ACCOUNT_RELATION__c.object
<CustomObject>
    <description>BST - Custom object to store M:M relations between Accounts (Customer and Competitors for wave 1). Most of the data provided by IMS, some data can be Baxter Specific.</description>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_START_DATE__c</fullName>
        <description>Start Date of the relation.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Related Account</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>BOOST Related Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INTEGRATION_LOG__c.object
<CustomObject>
    <description>Custom object used for IMS approval process for objects Account, Contact, AccountContactRelationShip, Account_Account_Relation__c</description>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_RELATED_ACCOUNT_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id to track the changes made for Account_Account_Relation__c object</description>
        <label>Related Account Id</label>
        <referenceTo>ACCOUNT_ACCOUNT_RELATION__c</referenceTo>
        <relationshipLabel>IMS Integration Logs</relationshipLabel>
        <relationshipName>IMS_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IMS Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000}</displayFormat>
        <label>BOOST Integration Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the User.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TgrIMSRelatedAccountFieldAuditTrg_Test.cls
//Akshay 11/23/2016
//Description - This class will be used for test coverage of TgrIMSRelatedAccountFieldAuditTrigger trigger on object Related Accounts.

@isTest
public class TgrIMSRelatedAccountFieldAuditTrg_Test{
    
    static testMethod void testAccountAccountRelationInsert(){
        test.starttest();
        ACCOUNT_ACCOUNT_RELATION__c aar = ClsTestDataUtility.createACCOUNT_ACCOUNT_RELATION();
        insert aar;
        List<INTEGRATION_LOG__c> iList = [select id, name,BST_RELATED_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_RELATED_ACCOUNT_ID__c =:aar.id ];
        if(iList.size()>0)
        system.assertEquals(aar.Id,iList[0].BST_RELATED_ACCOUNT_ID__c,'Error');
        test.stopTest();
    }
    
    static testMethod void testAccountAccountRelationUpdate(){
        test.startTest();
        ACCOUNT_ACCOUNT_RELATION__c aar = ClsTestDataUtility.createACCOUNT_ACCOUNT_RELATION();
        insert aar;
        aar.BST_COUNTRY__c = 'Belgium';
        update aar;
        List<INTEGRATION_LOG__c> iList = [select id, name,BST_RELATED_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_RELATED_ACCOUNT_ID__c =:aar.id ];
        if(iList.size()>0)
        system.assertEquals(aar.Id,iList[0].BST_RELATED_ACCOUNT_ID__c,'Error');
        test.stopTest();
    }  
    
    static testMethod void testAccountAccountRelationNonAdmInsert(){
        test.startTest();
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
         System.runAs(u){
            ACCOUNT_ACCOUNT_RELATION__c aar = ClsTestDataUtility.createACCOUNT_ACCOUNT_RELATION();
            insert aar;
            List<INTEGRATION_LOG__c> iList = [select id, name,BST_RELATED_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_RELATED_ACCOUNT_ID__c =:aar.id ];
            if(iList.size()>0)
            system.assertEquals(aar.Id,iList[0].BST_RELATED_ACCOUNT_ID__c,'Error');
        }
        test.stopTest();
    } 
    
    
    static testMethod void testAccountAccountRelationNonAdmUpdate(){
        test.startTest();
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u) {
            ACCOUNT_ACCOUNT_RELATION__c aar = ClsTestDataUtility.createACCOUNT_ACCOUNT_RELATION();
            insert aar;
            //aar.DP_START_DATE__c=system.today();
            update aar;
            List<INTEGRATION_LOG__c> iList = [select id, name,BST_RELATED_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_RELATED_ACCOUNT_ID__c =:aar.id ];
            if(iList.size()>0)
            system.assertEquals(aar.Id,iList[0].BST_RELATED_ACCOUNT_ID__c,'Error');
        }
        test.stopTest();
    } 
}