src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/VabletFieldSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ExceptionText__c</fullName>
        <label>ExceptionText</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query1__c</fullName>
        <label>Query1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Separator1__c</fullName>
        <label>Separator 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Separator2__c</fullName>
        <label>Separator 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant10__c</fullName>
        <label>Text Constant 10</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant11__c</fullName>
        <label>Text Constant 11</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant12__c</fullName>
        <label>Text Constant 12</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant13__c</fullName>
        <label>Text Constant 13</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant14__c</fullName>
        <label>Text Constant 14</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant15__c</fullName>
        <label>Text Constant 15</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant16__c</fullName>
        <label>Text Constant 16</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant1__c</fullName>
        <label>Text Constant 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant2__c</fullName>
        <label>Text Constant 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant3__c</fullName>
        <label>Text Constant 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant4__c</fullName>
        <label>Text Constant 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant5__c</fullName>
        <label>Text Constant 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant6__c</fullName>
        <label>Text Constant 6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant7__c</fullName>
        <label>Text Constant 7</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant8__c</fullName>
        <label>Text Constant 8</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextConstant9__c</fullName>
        <label>Text Constant 9</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat1__c</fullName>
        <label>Text Format 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat2__c</fullName>
        <label>Text Format 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat3__c</fullName>
        <label>Text Format 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat4__c</fullName>
        <label>Text Format 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat5__c</fullName>
        <label>Text Format 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextFormat6__c</fullName>
        <label>Text Format 6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type1__c</fullName>
        <label>Type 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type2__c</fullName>
        <label>Type 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type3__c</fullName>
        <label>Type 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Vablet Field Settings</label>
</CustomObject>

src/classes/VabletTestUtility.cls
public class VabletTestUtility {

	public static void createCustomSettings() {
		VabletFieldSettings__c testSettings1 = new VabletFieldSettings__c();
			testSettings1.Name = 'CustomContact';
			testSettings1.TextConstant1__c = '1111111111';
			testSettings1.Query1__c = 'SELECT Account.ID,Account.Account_Number__c,Account.Name,IsDeleted,Id,FirstName,LastName, Name,Email,MailingCity,MailingState,MailingCountry,MailingPostalCode,Phone FROM Contact WHERE Status__c = \'Active\' limit 9999 ALL ROWS';
			insert testSettings1;
		VabletFieldSettings__c testSettings2 = new VabletFieldSettings__c();
			testSettings2.Name = 'VabletTriggerHandler';
			testSettings2.TextConstant1__c = 'PDF';
			testSettings2.TextConstant2__c = '">';
			testSettings2.TextFormat1__c = '<br />File name (attached): <br />';
			testSettings2.TextFormat2__c = '<br />File name \\(attached\\): <br />';
			testSettings2.TextFormat3__c = '<br />';
			testSettings2.TextFormat4__c = '</a>';
			testSettings2.TextFormat5__c = '<br />File name: <br />';
			testSettings2.Separator1__c = ',';
			testSettings2.Separator2__c = '.';
			testSettings2.ExceptionText__c = '';
			insert testSettings2;
		VabletFieldSettings__c testSettings3 = new VabletFieldSettings__c();
			testSettings3.Name = 'VabletInterfaceV2';
			testSettings3.TextConstant1__c = 'supportsSecondaryContacts';
			testSettings3.TextConstant2__c = 'mappingValuesInOrder';
			testSettings3.TextConstant3__c = 'nonBlockingErrorMessage';
			testSettings3.TextConstant4__c = 'getEvents';
			testSettings3.TextConstant5__c = 'getMediaViews';
			testSettings3.TextConstant6__c = 'getContacts';
			testSettings3.TextConstant7__c = 'getContactFormatString';
			testSettings3.TextConstant8__c = 'getSalesForceDisplayMapping';
			testSettings3.TextConstant9__c = 'contactFormatString';
			testSettings3.TextConstant10__c = 'modificationDateAfter';
			testSettings3.TextConstant11__c = 'Accepted';
			testSettings3.TextConstant12__c = 'contactsAfterDate';
			testSettings3.TextConstant13__c = 'createdEvent';
			testSettings3.TextConstant14__c = 'contacts';
			testSettings3.TextConstant15__c = 'mediaViews';
			testSettings3.TextConstant16__c = 'events';
			testSettings3.TextFormat1__c = 'SecondaryContacts';
			testSettings3.TextFormat2__c = 'Secondary Contacts';
			testSettings3.TextFormat3__c = 'apexrest';
			testSettings3.TextFormat4__c = 'createEvent';
			testSettings3.TextFormat5__c = 'updateEvent';
			testSettings3.TextFormat6__c = '<LastName>, <FirstName> \n<email> \n<Phone>';
			testSettings3.Separator1__c = '\\/';
			testSettings3.Type1__c = 'datetime';
			testSettings3.Type2__c = 'string';
			testSettings3.Type3__c = 'picklist';
			testSettings3.Query1__c = 'SELECT Id, WhatId,WhoId,ShowAs, AccountId, Subject, StartDateTime, ReminderDateTime, Description, EndDateTime, Location,(SELECT EventId,Status, RelationId FROM EventRelations) FROM Event';
			insert testSettings3;
	}
}