src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INTEGRATION_LOG__c.object
<CustomObject>
    <description>Custom object used for IMS approval process for objects Account, Contact, AccountContactRelationShip, Account_Account_Relation__c</description>
    <fields>
        <fullName>BST_ACCOUNT_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id to track changes made for the Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IMS Integration Logs</relationshipLabel>
        <relationshipName>IMS_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BST_COMMENTS__c</fullName>
        <description>Stores the value of the IMS fields for which the Integration Log has been created.</description>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Approved</fullName>
                    <isActive>false</isActive>
                    <label>Baxter Approved</label>
                </value>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Approved</fullName>
                    <isActive>false</isActive>
                    <label>IMS Approved</label>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IMS Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000}</displayFormat>
        <label>BOOST Integration Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the User.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TgrIMSAccountFieldAuditTrigger_Test.cls
//Akshay 11/23/2016
//Description - This class will be used for test coverage of TgrIMSAccountFieldAuditTrigger trigger on object Account

@isTest
public class TgrIMSAccountFieldAuditTrigger_Test{

    static testMethod void testAccountInsert(){
    
        test.startTest();
        
        Account acc = ClsTestDataUtility.createAccount('Belgium');
        Schema.DescribeSObjectResult d = Schema.SObjectType.Account;
        Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('IMS Account');
        acc.recordtypeid=rtByName.getRecordTypeId();
        insert acc;
        List<INTEGRATION_LOG__c> iList = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc.id limit 1];
        if(iList.size()>0)
        system.assertEquals(acc.Id,iList[0].BST_ACCOUNT_ID__c,'Error');
        test.stopTest();
    }
    
    static testMethod void testAccountUpdate(){
        test.startTest();
        
        Account acc = ClsTestDataUtility.createAccount('Belgium');
        Schema.DescribeSObjectResult d = Schema.SObjectType.Account;
        Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
        Schema.RecordTypeInfo rtByName =  rtMapByName.get('IMS Account');
        acc.recordtypeid=rtByName.getRecordTypeId();
        insert acc;
        acc.billingCountry = 'Germany';
        update acc;
        List<INTEGRATION_LOG__c> iList = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc.id limit 1];
        if(iList.size()>0)
        system.assertEquals(acc.Id,iList[0].BST_ACCOUNT_ID__c,'Error');
        system.assertEquals('Germany',acc.BillingCountry,'Country updation failed');
        test.stopTest();
    }
    
    static testMethod void testAccountNonAdminInsert(){
        test.startTest();
        
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u)
        {
            Account acc = ClsTestDataUtility.createAccount('Belgium');
            Schema.DescribeSObjectResult d = Schema.SObjectType.Account;
            Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
            Schema.RecordTypeInfo rtByName =  rtMapByName.get('IMS Account');
            acc.recordtypeid=rtByName.getRecordTypeId();
            insert acc;
            List<INTEGRATION_LOG__c> iList = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc.id limit 1];
           // system.assertEquals(acc.Id,iList[0].BST_ACCOUNT_ID__c,'Error');
        }
        
        test.stopTest();  
    }
    
    static testMethod void testAccountNonAdminUpdate(){
        test.startTest();
        
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u)
        {
            Account acc = ClsTestDataUtility.createAccount('Belgium');
            Schema.DescribeSObjectResult d = Schema.SObjectType.Account;
            Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
            Schema.RecordTypeInfo rtByName =  rtMapByName.get('IMS Account');
            acc.recordtypeid=rtByName.getRecordTypeId();
            insert acc;
            acc.billingCountry = 'Germany';
            update acc;
            List<INTEGRATION_LOG__c> iList = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc.id limit 1];
            if(iList.size()>0)
            system.assertEquals(acc.Id,iList[0].BST_ACCOUNT_ID__c,'Error');
            system.assertEquals('Germany',acc.BillingCountry,'Country updation failed');
        }   
        test.stopTest();  
    }
    
    static testMethod void testImsIntegrationLogUpdate(){
        test.startTest();
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u)
        {
            Account acc = ClsTestDataUtility.createAccount('Belgium');
            INTEGRATION_LOG__c iLog = ClsTestDataUtility.createINTEGRATION_LOG();
            ilog.BST_ACCOUNT_ID__c=acc.id;
            insert iLog;
            iLog.BST_COMMENTS__c = 'Test BST Comments';
            iLog.BST_STATUS__c = 'Baxter Pending Review';
            update iLog;
            system.assertEquals(iLog.BST_Country__c,acc.BST_Country__c,'Country Not Updated');
        }
        test.stopTest();               
    }
}