src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_Account_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Contact.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_GENDER__c</fullName>
        <description>IMS COM - Male - Female</description>
        <inlineHelpText>IMS COM - Male - Female</inlineHelpText>
        <label>IMS Ind. Gender</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_PROFESSIONAL_TYPE__c</fullName>
        <description>IMS COM - The primary means of identifying a healthcare professional. The Professional Type has replaced the Class code (TYT) as it offers more granularity. Ex. Physician, Dentist, Nurse, Administrator</description>
        <inlineHelpText>IMS COM - The primary means of identifying a healthcare professional. The Professional Type has replaced the Class code (TYT) as it offers more granularity. Ex. Physician, Dentist, Nurse, Administrator</inlineHelpText>
        <label>IMS Ind. Prof. Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Allied Health Professionals</fullName>
                </value>
                <value>
                    <fullName>Dental Assistant</fullName>
                </value>
                <value>
                    <fullName>Dental Prosthetist</fullName>
                    <isActive>false</isActive>
                    <label>Dental Prosthetist</label>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Midwife</fullName>
                </value>
                <value>
                    <fullName>Non-HCP</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paramedical</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist Assistant</fullName>
                </value>
                <value>
                    <fullName>Physical Therapist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physician Assistant</fullName>
                    <isActive>false</isActive>
                    <label>Physician Assistant</label>
                </value>
                <value>
                    <fullName>Researcher/Scientist</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Veterinarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_STATE__c</fullName>
        <description>IMS COM - Situation of the healthcare professional: Active, Inactive, Retired</description>
        <inlineHelpText>IMS COM - Situation of the healthcare professional: Active, Inactive, Retired</inlineHelpText>
        <label>IMS Ind. State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Is opening</fullName>
                    <isActive>false</isActive>
                    <label>Is opening</label>
                </value>
                <value>
                    <fullName>Maternity/Paternity Leave</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Reduced Activity</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Temporarily Closed</fullName>
                    <isActive>false</isActive>
                    <label>Temporarily Closed</label>
                </value>
                <value>
                    <fullName>Temporarily Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_STATUS__c</fullName>
        <description>Controlling field for Ind State</description>
        <inlineHelpText>Status of the Individual (Contact) as provided by IMS</inlineHelpText>
        <label>IMS Ind. Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INTEGRATION_LOG__c.object
<CustomObject>
    <description>Custom object used for IMS approval process for objects Account, Contact, AccountContactRelationShip, Account_Account_Relation__c</description>
    <fields>
        <fullName>BST_ACCOUNT_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id to track changes made for the Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IMS Integration Logs</relationshipLabel>
        <relationshipName>IMS_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IMS Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000}</displayFormat>
        <label>BOOST Integration Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>The value is fetched from Global Value Set BST_COUNTRY_GLOBAL. This field is used in visibility fielters for My Profile/All profile views and also this is used in sharing rules so that the users can see the correct set of questions based on the country/countries they cover</description>
        <inlineHelpText>The country where the question needs to be visible</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BST_Country</valueSetName>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>BST_Global_Question</fullName>
        <active>true</active>
        <description>Used as a parent question</description>
        <label>Global Question</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsLookupSObjectController_Test.cls
// Akshay 11/25/2016
// Description - This class will be used for test coverage of ClsLookupSObjectController.

@isTest
public class ClsLookupSObjectController_Test{

    Static testMethod void Test_ClsLookupSObjectController1(){
        test.startTest();
        Account acc1 = new Account(RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMS Account').getRecordTypeId(), 
                          Name = 'Test Account1',BST_COUNTRY__c = 'Belgium', billingStreet = 'Test 123', BST_Account_Number__c='12' ,
                          billingState = 'Test State', billingCountry = 'Test Country', billingCity = 'Test City', billingPostalCode = '1111');
        insert acc1;
        
        List<INTEGRATION_LOG__c> iList1 = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc1.id limit 1];
        if(iList1.size()>0)
        system.assertEquals(acc1.Id,iList1[0].BST_ACCOUNT_ID__c,'Error');
        system.assertEquals('Belgium',acc1.BST_Country__c,'Country updation failed'); 
        
        Account acc2 = new Account(RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMS Account').getRecordTypeId(), 
                          Name = 'Test Account2',BST_COUNTRY__c = 'Belgium', billingStreet = 'Test 123', BST_Account_Number__c='1',
                          billingState = 'Test State', billingCountry = 'Test Country', billingCity = 'Test City', billingPostalCode = '1111');
        insert acc2;
        
        List<INTEGRATION_LOG__c> iList2 = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc2.id limit 1];
        if(iList2.size()>0)
        system.assertEquals(acc2.Id,iList2[0].BST_ACCOUNT_ID__c,'Error');
        system.assertEquals('Belgium',acc2.BST_Country__c,'Country updation failed'); 
        
        Contact con1 = new Contact(RecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IMS Contact').getRecordTypeId(), 
                          Salutation = 'Mr.', FirstName = 'First Test', LastName = 'Last Test', AccountId = acc1.Id, 
                          DP_IND_GENDER__c = 'Male', DP_IND_STATUS__c = 'Valid', DP_IND_STATE__c = 'Active', DP_IND_PROFESSIONAL_TYPE__c = 'Nurse', 
                          DP_IND_SPEC_1__c = 'Student', BST_COUNTRY__c = 'Belgium');
        insert con1;
        
        AccountContactRelation acr = new AccountContactRelation();
        acr.AccountId = acc2.Id;
        acr.ContactId = con1.Id;
        acr.BST_COUNTRY__c = 'Belgium';
        system.debug('Value of acc2:' +acc2.Id);
        insert acr;    
      
        Test.setFixedSearchResults(new List<id>{acc2.Id});
        ClsLookupSObjectController.lookup('Test','Account','IMSAccount' ,'Name,billingState,billingCountry',con1.id,true);   
        test.stopTest(); 
   }
   
   Static testMethod void Test_ClsLookupSObjectController2(){
       
        test.startTest();
        Account acc1 = new Account(RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMS Account').getRecordTypeId(), 
                          Name = 'Test Account1',BST_COUNTRY__c = 'Belgium', billingStreet = 'Test 123', BST_Account_Number__c='12',
                          billingState = 'Test State', billingCountry = 'Test Country', billingCity = 'Test City', billingPostalCode = '1111');
        insert acc1;
      
        Account acc2 = new Account(RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMS Account').getRecordTypeId(), 
                          Name = 'Test Account2',BST_COUNTRY__c = 'Belgium', billingStreet = 'Test 123', BST_Account_Number__c='1' ,
                          billingState = 'Test State', billingCountry = 'Test Country', billingCity = 'Test City', billingPostalCode = '1111');
        insert acc2;
      
        Contact con1 = new Contact(RecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IMS Contact').getRecordTypeId(), 
                          Salutation = 'Mr.', FirstName = 'First Test', LastName = 'Last Test', AccountId = acc1.Id, 
                          DP_IND_GENDER__c = 'Male', DP_IND_STATUS__c = 'Valid', DP_IND_STATE__c = 'Active', DP_IND_PROFESSIONAL_TYPE__c = 'Nurse', 
                          DP_IND_SPEC_1__c = 'Student', BST_COUNTRY__c = 'Belgium');
        insert con1;
      
        AccountContactRelation acr = new AccountContactRelation();
        acr.AccountId = acc2.Id;
        acr.ContactId = con1.Id;
        acr.BST_COUNTRY__c = 'Belgium';        
        insert acr;    
        
        system.assertEquals(acc2.Id,acr.AccountId,'Insertion Failed');
        system.assertEquals(con1.Id,acr.ContactId,'Insertion Failed');
        
        Test.setFixedSearchResults(new List<id>{con1.Id});
        ClsLookupSObjectController.lookup('First Test','Contact','IMSContact' ,'FirstName',acc2.id ,true); 
        test.stopTest();   
   }
       // This is to cover the code of the class ClsLookupSObjectController (question object)
       Static testMethod void Test_ClsLookupSObjectController3() {  
        Test.startTest();
        list<Question__c> questobj = TestClassHelper.createQuestionRecs();
        system.assert(questobj.size()>0);
        /*
        list<Question__c> questobj2 = new list<Question__c>();
        for(Question__c obb:questobj){
            //obb.RecordType.DeveloperName = 'BST_Global_Question';
            obb.BST_Status__c = 'Active';
            questobj2.add(obb);
        }
        update questobj2;
        */
        ClsLookupSObjectController.lookup('Test','Question__c','AccountProfileQuestion','Name',questobj[0].id,True);        
        
        Test.StopTest();

       }
}