src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BST_Account_Number__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_WKP_STRUCTURE_TYPE__c</fullName>
        <description>IMS COMMON - Indentifies the workplaces organizational level within a hierarchy structure. In Onekey, a workplace can be a single-level entity, e.g. a private practice, but also a department, a group of departments, or a group of organizations.</description>
        <inlineHelpText>IMS COMMON - Indentifies the workplaces organizational level within a hierarchy structure. In Onekey, a workplace can be a single-level entity, e.g. a private practice, but also a department, a group of departments, or a group of organizations.</inlineHelpText>
        <label>IMS Wkp. Structure Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Association, Fellowship</fullName>
                </value>
                <value>
                    <fullName>Department</fullName>
                </value>
                <value>
                    <fullName>Group of Organisations</fullName>
                </value>
                <value>
                    <fullName>Instances, Committees</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous, Unqualified</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Organisation</fullName>
                </value>
                <value>
                    <fullName>Sub Department, Unit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BST_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BST_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BXGO_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BXGO_Tender_Issued__c</fullName>
        <label>Tender Issued</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Trigger_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Trigger Settings</label>
</CustomObject>

src/classes/LtngCtrlAccountProfile_Test.cls
/********************************************************************************
Apex Class Name - LtngCtrlAccountProfile_Test
Version - 1.0
Created Date - Nov 3rd, 2016
Function - Test class for  LtngCtrlAccountProfile 
Modification Log : 
--------------------------------------------------------------------------------
* Developer               Date                 Description
* -------------------     ------------         -----------------------
* Dharani Pothula         11/03/2016           Original Version
* Shashank Mehra          13-june-2017         Added code for account and opportuity records insertion.
*******************************************************************************/

@isTest
public class LtngCtrlAccountProfile_Test {
    
    /**
    * Method Name: testGetAccount_ReturnAccount
    * Description: Checks for the current Account 
    * Parameter: None                             
    * Return Type: Account
    */
    public static testMethod void testGetAccount_ReturnAccount(){
        //Create Account with Account Number aNum1234
        
        Test.startTest();
        
        Account acc = new account();
        acc.Name = 'test name';
        acc.BST_COUNTRY__c = 'Belgium';
        acc.BST_Account_Number__c = 'aNum12345';
        acc.DP_WKP_STRUCTURE_TYPE__c = 'Organisation';
        acc.BillingStreet = 'test address';
        acc.BillingCity = 'test city';
        acc.BillingPostalCode = '102011';
        acc.BillingCountry = 'test country';
        insert acc;
        
        Opportunity Opp = new Opportunity();
        Opp.AccountId = acc.Id;
        Opp.name = 'Test Opp';
        Opp.StageName = 'Prospect';
        Opp.Closedate = date.today();
        Opp.BXGO_Country__c = 'Belgium';
        Opp.BXGO_Tender_Issued__c = date.today();
        insert Opp;
        
        
        Account testAccount = TestClassHelper.creatAccount();
        LtngCtrlAccountProfile.checkPermission();
        
        Account acc1 = LtngCtrlAccountProfile.getAccount(testAccount.Id);
        
        LtngCtrlAccountProfile.getAccountFromOpp(Opp.Id);
        
        system.assertEquals('aNum12345', acc.BST_Account_Number__c);  // Modified by Shashank
        Test.stopTest();
    }
    
    /**
    * Method Name: testGetOppty_ReturnAccount
    * Description: Checks for the oppty current Account 
    * Parameter: None                             
    * Return Type: Account
    */
    /*
    public static testMethod void testGetOppty_ReturnAccount(){
        //Create Account with Account Number aNum1234
        List<sObject> ls = Test.loadData(Trigger_Settings__c.sObjectType, 'ApexTestClassDataLoad_TriggerSettings');
        Opportunity testOpty = TestClassHelper.createOpportunity();
        testOpty.AccountId = TestClassHelper.accSList[0].Id;
        update testOpty;
        Account acc = LtngCtrlAccountProfile.getAccountFromOpp(testOpty.Id);
        system.assertEquals('aNum1234', acc.Account_Number__c);
        
    }
    */
    /** 
    * Method Name: getUIThemeDescription_ReturnString
    * Description: Checks for the current Theme 
    * Parameter: None                             
    * Return Type: String
    */
    public static testMethod void getUIThemeDescription_ReturnString(){
     
        String theme = LtngCtrlAccountProfile.getUIThemeDescription();
        
        system.assert(!string.isBlank(theme));
        
    }
}