src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_BAX_SALES_TEAM__c</fullName>
        <description>BST – Field to define the main Baxter team/Franchise for the user</description>
        <label>Baxter Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bax Company/Services</fullName>
                </value>
                <value>
                    <fullName>HC - Anesthesia/Critical Care</fullName>
                </value>
                <value>
                    <fullName>HC - BioSurgery</fullName>
                </value>
                <value>
                    <fullName>HC - Glob.Pharma Injectables</fullName>
                </value>
                <value>
                    <fullName>HC - Infusion Systems</fullName>
                </value>
                <value>
                    <fullName>HC - IV Therapies/SVP</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition Pediatrics</fullName>
                </value>
                <value>
                    <fullName>HC - Pharmacy Services</fullName>
                </value>
                <value>
                    <fullName>HC - Productivity Sys</fullName>
                    <isActive>false</isActive>
                    <label>HC - Productivity Sys</label>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                    <isActive>false</isActive>
                    <label>Market Access</label>
                </value>
                <value>
                    <fullName>MSL/Medical</fullName>
                    <isActive>false</isActive>
                    <label>MSL/Medical</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RE - Acute</fullName>
                </value>
                <value>
                    <fullName>RE - Hemo Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Peritoneal Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Water Treatment</fullName>
                </value>
                <value>
                    <fullName>Small Volume Parenterals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Event_Details__mdt.object
<CustomObject>
    <fields>
        <fullName>BST_BAX_SALES_TEAM__c</fullName>
        <description>This tracks the default value for Event type per record type</description>
        <label>Event Type Default Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BST_CALL_TYPE__c</fullName>
        <description>Field tracks possible values for Event Type per record type</description>
        <label>Event Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>BST_MAIN_TOPIC__c</fullName>
        <description>This field tracks the Main Topic from Event</description>
        <label>Main Topic</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RecordTypeName__c</fullName>
        <label>Record Type Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>Field Customer Calls</fullName>
                </value>
                <value>
                    <fullName>Non Field Customer Activity</fullName>
                </value>
                <value>
                    <fullName>Field Training Activity</fullName>
                </value>
                <value>
                    <fullName>Internal/ Non-Customer Activity</fullName>
                </value>
                <value>
                    <fullName>Visite commerciale sur le terrain</fullName>
                </value>
                <value>
                    <fullName>Activité interneon commerciale</fullName>
                </value>
                <value>
                    <fullName>Activités commerciales hors terrain</fullName>
                </value>
                <value>
                    <fullName>Formation fournie</fullName>
                </value>
                <value>
                    <fullName>Müşteri Ziyaret Alanı</fullName>
                </value>
                <value>
                    <fullName>Saha Eğitim Faaliyetleri</fullName>
                </value>
                <value>
                    <fullName>Şirket içi Etkinlik</fullName>
                </value>
                <value>
                    <fullName>Alan Dışı Müşteri Aktivitesi</fullName>
                </value>
                <value>
                    <fullName>Field Sales Calls</fullName>
                    <isActive>false</isActive>
                    <label>Field Sales Calls</label>
                </value>
                <value>
                    <fullName>Internal/ Non-Sales Activity</fullName>
                    <isActive>false</isActive>
                    <label>Internal/ Non-Sales Activity</label>
                </value>
                <value>
                    <fullName>Non Field Sales Activity</fullName>
                    <isActive>false</isActive>
                    <label>Non Field Sales Activity</label>
                </value>
                <value>
                    <fullName>Training Provided</fullName>
                    <isActive>false</isActive>
                    <label>Training Provided</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event Details</label>
    <pluralLabel>Event Details</pluralLabel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <fields>
        <fullName>BST_CATEGORY__c</fullName>
        <description>The pick list is dependent on Major Category pick-list. This field can be used to group questions into logical streams and is used for grouping into My Profile/all Profile screens under Account and Contact</description>
        <inlineHelpText>Field dependent on selection made in Major Category. The value allows logical grouping of the questions</inlineHelpText>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_MAJOR_CATEGORY__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Competitive information</fullName>
                </value>
                <value>
                    <fullName>CRRT Baxter Insight</fullName>
                </value>
                <value>
                    <fullName>CRRT Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>General Account information</fullName>
                </value>
                <value>
                    <fullName>HD Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>PD Baxter Insight</fullName>
                </value>
                <value>
                    <fullName>PD Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>Vial-Mate, Frozen, Vanco Dex</fullName>
                </value>
                <value>
                    <fullName>Gas</fullName>
                </value>
                <value>
                    <fullName>Baxter Data</fullName>
                </value>
                <value>
                    <fullName>Hospital Potential</fullName>
                </value>
                <value>
                    <fullName>Profiling</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Home Based Hemodialysis Therapies</fullName>
                </value>
                <value>
                    <fullName>Key Metrics</fullName>
                </value>
                <value>
                    <fullName>Unit Assessment</fullName>
                </value>
                <value>
                    <fullName>Treatment Criteria</fullName>
                </value>
                <value>
                    <fullName>Delivered CRRT Dose</fullName>
                </value>
                <value>
                    <fullName>Fluid Overload</fullName>
                </value>
                <value>
                    <fullName>Recirculation</fullName>
                </value>
                <value>
                    <fullName>SLED Threat</fullName>
                </value>
                <value>
                    <fullName>Common Settings</fullName>
                </value>
                <value>
                    <fullName>Anticoagulation</fullName>
                </value>
                <value>
                    <fullName>Additional Information</fullName>
                </value>
                <value>
                    <fullName>Unit Specific Information</fullName>
                </value>
                <value>
                    <fullName>Short Term Catheter</fullName>
                </value>
                <value>
                    <fullName>Prismaflex Custom Mode</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_MAJOR_CATEGORY__c</fullName>
        <description>BST - pick list dependent on Country. Used to allow grouping of questions into logical buckets</description>
        <inlineHelpText>Pick list used to group questions in logical segments. The grouping will be done into My Profile/All Profile</inlineHelpText>
        <label>Major Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CRRT</fullName>
                </value>
                <value>
                    <fullName>Surgery</fullName>
                </value>
                <value>
                    <fullName>Anesthesia</fullName>
                </value>
                <value>
                    <fullName>Renal</fullName>
                </value>
                <value>
                    <fullName>Advanced Surgery</fullName>
                </value>
                <value>
                    <fullName>Medical Affairs (MSL)</fullName>
                </value>
                <value>
                    <fullName>Renal Chronic Census</fullName>
                </value>
                <value>
                    <fullName>HP - Fluid Systems</fullName>
                </value>
                <value>
                    <fullName>Nurse Worksheet</fullName>
                </value>
                <value>
                    <fullName>Anestetics</fullName>
                    <isActive>false</isActive>
                    <label>Anestetics</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_QUESTION_TYPE__c</fullName>
        <description>BST - picklist set on Global Question (parent Question) to allow categorization of the initiative in like Global, REgional, cluster level etc. Mainly important for reporting</description>
        <inlineHelpText>Picklist to allow categorization of Global Questions (Parent Question) into groups like Global, Regional, Cluster initiatives etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Benelux Initiative</fullName>
                </value>
                <value>
                    <fullName>EMEA Initiative</fullName>
                </value>
                <value>
                    <fullName>Global Initiative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_RESPONSE_TYPE__c</fullName>
        <description>BST - This is a picklist used to capture the response type of any question. It allows Date, Number, Picklist, Multipicklist</description>
        <inlineHelpText>Field used to define what type of answer can be provided for the question. Can be only one of the following: Date, Number, Picklist or Multipicklist</inlineHelpText>
        <label>Response Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Multi Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsApexUtil.cls
public class ClsApexUtil 
{
//Jagan 10/14/2016
//Description - This class will be the Utility class with methods used by various apex classes in application
//Change Log : Arpit Agarwal 5/30/2017 - Wave 2
    
    //One comment - Satty Cha Comment
    //Gets all record types by SObject
    public static Map<String, Schema.RecordTypeInfo> getRecordTypeBySObject(String apiName)
    {
        return Schema.getGlobalDescribe().get(apiName).getDescribe().getRecordTypeInfosByName();
    }
    //Gets a specific RecordType by SObject name/Label
    public static Id getRecordTypeId(String objApiName, String recordTypeLabel)
    {
        return getRecordTypeBySObject(objApiName).get(recordTypeLabel).getRecordTypeId();
    }
    //Method to get the definition of the Fields for a given SObjectType
    public static Map<String, Schema.SObjectField> getFieldsSetMap (String objectType)
    {
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType sObjectSchema = schemaMap.get(objectType);
        Map<String, Schema.SObjectField> fieldsSetMap = sObjectSchema.getDescribe().fields.getMap();
        return fieldsSetMap;
    }  
    //Method used to submit the record for approval
    public static void submitForApproval(String sObjectId, String comments, List<User> approvers)
    {
        // Create an approval request for the sObject
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments(comments);
        req1.setObjectId(sObjectId);
        req1.setNextApproverIds(new Id[] {approvers[0].Id});
        // Submit the approval request for the Opportunity
        Approval.ProcessResult result = Approval.process(req1);
    
    }
    //Method used to get ProcessInstanceWorkItemId using SOQL
    public static Id getWorkItemId(Id targetObjectId)
    {
        Id retVal = null;

        for(ProcessInstanceWorkitem workItem  : [Select p.Id from ProcessInstanceWorkitem p
            where p.ProcessInstance.TargetObjectId =: targetObjectId])
            retVal  =  workItem.Id;
        return retVal;
    }
    //Method used to get ProcessInstanceWorkItemId using SOQL
    public static void rejectRecord(SObject sObj, String comments)
    {
        Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
        req.setComments(comments);
        req.setAction('Reject');
        Id workItemId = getWorkItemId(sObj.id);   
    
        if(workItemId != null)
        {   
            req.setWorkitemId(workItemId);
            // Reject the record, which is in approval
            Approval.ProcessResult result =  Approval.process(req);
        }
    }
    //Method will insert a chatter feed for a given Salesforce record
    public static void addFeedItemToRecord (Id sObjectId, String comments)
    {
        FeedItem post = new FeedItem();
        post.ParentId = sObjectId;
        post.Body = comments;
        insert post;
    }
     
     
        //Method will insert a chatter feed only for rejection for a given Salesforce record also @mention the country Admin
    public static void addFeedItemToRecord(Id sObjectId, String comments, String CountryAdminId){
        FeedItem post = new FeedItem();
        post.ParentId = sObjectId;
        post.Body = comments;
        insert post;
       if(!Test.isRunningTest()){
        ConnectApi.CommentInput commentInput = new ConnectApi.CommentInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();        
        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();        
        mentionSegmentInput.id = CountryAdminId;// this will be ID of country admin 
        messageBodyInput.messageSegments.add(mentionSegmentInput);
        
        commentInput.body = messageBodyInput;
        
        ConnectApi.Comment commentRep = ConnectApi.ChatterFeeds.postCommentToFeedElement(null, post.id, commentInput,null);// this yellow will be id of feeditem
      }
    } 
    //Method returning the label to value combination for Event object
    public static Map<String, String> picklistLableValueMap (String fieldName)
    {
        Schema.DescribeFieldResult fieldResult;
        Map<String, String> pickListLabelValueMap = new Map<String, String>();
        //Schema.DescribeFieldResult fieldResult = Event.fieldName.getDescribe();
        // Get the describe result for the Type field on the Account object
        if(fieldName == 'BST_CALL_TYPE__C')
            fieldResult = Event.BST_CALL_TYPE__C.getDescribe();
        else if(fieldName == 'BST_BAX_SALES_TEAM__C')
            fieldResult = Event.BST_BAX_SALES_TEAM__C.getDescribe();
        else if(fieldName == 'BST_MAIN_TOPIC__C')
            fieldResult = Event.BST_MAIN_TOPIC__C.getDescribe();
        
        List<Schema.PicklistEntry> pickListEntry = fieldResult.getPicklistValues();
        for(Integer contrIndex=0; contrIndex<pickListEntry.size(); contrIndex++)
        {            
            Schema.PicklistEntry ctrlentry = pickListEntry[contrIndex];
            pickListLabelValueMap.put(ctrlentry.getLabel(), ctrlentry.getValue());
        }   
        return pickListLabelValueMap;
    }
    //Method gets all possible picklist values for the Event recordtype
    public static Set<String> getPossibleLOVs (String recordTypeName, String fieldName)
    {
        List<Event_Details__mdt> evtDetailsListForRecdType = new List<Event_Details__mdt>();
        If(fieldName == 'BST_BAX_SALES_TEAM__c')
            evtDetailsListForRecdType = [SELECT RecordTypeName__c, BST_BAX_SALES_TEAM__c FROM Event_Details__mdt WHERE MasterLabel = : recordTypeName];
        else If(fieldName == 'BST_MAIN_TOPIC__c')
            evtDetailsListForRecdType = [SELECT RecordTypeName__c, BST_MAIN_TOPIC__c FROM Event_Details__mdt WHERE MasterLabel = : recordTypeName];
        else If(fieldName == 'BST_CALL_TYPE__c')
            evtDetailsListForRecdType = [SELECT RecordTypeName__c, BST_CALL_TYPE__c FROM Event_Details__mdt WHERE MasterLabel = : recordTypeName];
        
        
        Set<String> eventFieldSet = new Set<String>();
        for(Event_Details__mdt evtFields : evtDetailsListForRecdType)
        {
            String possibleValues;
            If(fieldName == 'BST_BAX_SALES_TEAM__c')
                possibleValues = evtFields.BST_BAX_SALES_TEAM__c;
            else If(fieldName == 'BST_MAIN_TOPIC__c')
                possibleValues = evtFields.BST_MAIN_TOPIC__c;
            else If(fieldName == 'BST_CALL_TYPE__c')
                possibleValues = evtFields.BST_CALL_TYPE__c;
            
            if(possibleValues!= null && possibleValues.split(';').size() > 1)
            {
                for(String value : possibleValues.split(';'))
                {
                    if(value != '' )
                        eventFieldSet.add(value);
                }
            }
        }
        system.debug('Possible size of getPossibleLOVs is ' + eventFieldSet.size());
        return eventFieldSet;
    }
  public static void countryAndTeamCheck (String userCountry, String primCountry, String usrSecCountry, List<sObject> sObjList)
  {
   for(sObject sObj : sObjList)
   {
       if(usrSecCountry==null)
       {
           if (userCountry != primCountry)
            {
               sObj.addError(System.Label.BST_Country_Validation);       
            }
       }
        else
        {
            if(userCountry != primCountry && !usrSecCountry.contains(primCountry))    
            {
               sObj.addError(System.Label.BST_Country_Validation);             
            }
        }    
   }
  }
  
  public static Map<String, String> picklistMap (String fieldName)
    {
        Schema.DescribeFieldResult fieldResult;
        Map<String, String> pickListLabelValueMap = new Map<String, String>();
        //Schema.DescribeFieldResult fieldResult = Question__c.fieldName.getDescribe();
        // Get the describe result for the Picklist fields on the Question object
        if(fieldName == 'BST_CATEGORY__c')
            fieldResult = Question__c.BST_CATEGORY__c.getDescribe();
        else if(fieldName == 'BST_MAJOR_CATEGORY__c')
            fieldResult = Question__c.BST_MAJOR_CATEGORY__c.getDescribe();
        else if(fieldName == 'BST_QUESTION_TYPE__c')
            fieldResult = Question__c.BST_QUESTION_TYPE__c.getDescribe();
        else if(fieldName == 'BST_RESPONSE_TYPE__c')
            fieldResult = Question__c.BST_RESPONSE_TYPE__c.getDescribe();
        else if(fieldName == 'BST_SALESFORCE_GROUP__c')
            fieldResult = Question__c.BST_SALESFORCE_GROUP__c.getDescribe();
        else if(fieldName == 'BST_SALES_PROCESS__c')
            fieldResult = Question__c.BST_SALES_PROCESS__c.getDescribe();
        else if(fieldName == 'BST_STATUS__c')
            fieldResult = Question__c.BST_STATUS__c.getDescribe();
            
        List<Schema.PicklistEntry> pickListEntry = fieldResult.getPicklistValues();
        for(Integer contrIndex=0; contrIndex<pickListEntry.size(); contrIndex++)
        {            
            Schema.PicklistEntry ctrlentry = pickListEntry[contrIndex];
            pickListLabelValueMap.put(ctrlentry.getLabel(), ctrlentry.getValue());
        }   
        system.debug('pickListLabelValueMap' + pickListLabelValueMap);
        return pickListLabelValueMap;
    }
}