src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Contact.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_GENDER__c</fullName>
        <description>IMS COM - Male - Female</description>
        <inlineHelpText>IMS COM - Male - Female</inlineHelpText>
        <label>IMS Ind. Gender</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_PROFESSIONAL_TYPE__c</fullName>
        <description>IMS COM - The primary means of identifying a healthcare professional. The Professional Type has replaced the Class code (TYT) as it offers more granularity. Ex. Physician, Dentist, Nurse, Administrator</description>
        <inlineHelpText>IMS COM - The primary means of identifying a healthcare professional. The Professional Type has replaced the Class code (TYT) as it offers more granularity. Ex. Physician, Dentist, Nurse, Administrator</inlineHelpText>
        <label>IMS Ind. Prof. Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Allied Health Professionals</fullName>
                </value>
                <value>
                    <fullName>Dental Assistant</fullName>
                </value>
                <value>
                    <fullName>Dental Prosthetist</fullName>
                    <isActive>false</isActive>
                    <label>Dental Prosthetist</label>
                </value>
                <value>
                    <fullName>Dentist</fullName>
                </value>
                <value>
                    <fullName>Medical Assistant</fullName>
                </value>
                <value>
                    <fullName>Midwife</fullName>
                </value>
                <value>
                    <fullName>Non-HCP</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Optician</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paramedical</fullName>
                </value>
                <value>
                    <fullName>Pharmacist</fullName>
                </value>
                <value>
                    <fullName>Pharmacist Assistant</fullName>
                </value>
                <value>
                    <fullName>Physical Therapist</fullName>
                </value>
                <value>
                    <fullName>Physician</fullName>
                </value>
                <value>
                    <fullName>Physician Assistant</fullName>
                    <isActive>false</isActive>
                    <label>Physician Assistant</label>
                </value>
                <value>
                    <fullName>Researcher/Scientist</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
                <value>
                    <fullName>Veterinarian</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_SPEC_1__c</fullName>
        <description>IMS COM -Primary specialty practiced by the healthcare professional. most cases, the officially recognized specialty However, because this field is mandatory in OneKey, some individuals have a default primary specialty that is not recognized officially</description>
        <inlineHelpText>IMS COM -Primary specialty practiced by the healthcare professional. most cases, the officially recognized specialty However, because this field is mandatory in OneKey, some individuals have a default primary specialty that is not recognized officially</inlineHelpText>
        <label>IMS Ind. Speciality 1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Abdominal / Digestive Surgery</fullName>
                </value>
                <value>
                    <fullName>Accident &amp; Emergency</fullName>
                </value>
                <value>
                    <fullName>Acupuncture</fullName>
                </value>
                <value>
                    <fullName>Acute Medicine</fullName>
                </value>
                <value>
                    <fullName>Addictology</fullName>
                </value>
                <value>
                    <fullName>Administration</fullName>
                </value>
                <value>
                    <fullName>Administrative Director</fullName>
                </value>
                <value>
                    <fullName>Aesthetic Medicine</fullName>
                </value>
                <value>
                    <fullName>Allergology</fullName>
                </value>
                <value>
                    <fullName>Ambulance</fullName>
                </value>
                <value>
                    <fullName>Anaesthesiology</fullName>
                </value>
                <value>
                    <fullName>Anaesthesiology Nurse</fullName>
                </value>
                <value>
                    <fullName>Anatomical Pathology</fullName>
                </value>
                <value>
                    <fullName>Andrology</fullName>
                </value>
                <value>
                    <fullName>Anesthesiology</fullName>
                </value>
                <value>
                    <fullName>Anesthetic Nurse</fullName>
                </value>
                <value>
                    <fullName>Angiology</fullName>
                </value>
                <value>
                    <fullName>Aprentice Chemist Assistant</fullName>
                </value>
                <value>
                    <fullName>Aviation / Aerospacial Medecine</fullName>
                </value>
                <value>
                    <fullName>Bacteriology</fullName>
                </value>
                <value>
                    <fullName>Biochemistry</fullName>
                </value>
                <value>
                    <fullName>Biology</fullName>
                </value>
                <value>
                    <fullName>BioMedical Engineer</fullName>
                </value>
                <value>
                    <fullName>Biomedical Technician</fullName>
                </value>
                <value>
                    <fullName>Biophysics</fullName>
                </value>
                <value>
                    <fullName>Biostatistics</fullName>
                </value>
                <value>
                    <fullName>Cardiology</fullName>
                </value>
                <value>
                    <fullName>Cardio Surgery</fullName>
                </value>
                <value>
                    <fullName>Cardiothoracic/ Thoracic Surgery</fullName>
                </value>
                <value>
                    <fullName>Cardiovascular/Vascular Surgery</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Student</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_STATE__c</fullName>
        <description>IMS COM - Situation of the healthcare professional: Active, Inactive, Retired</description>
        <inlineHelpText>IMS COM - Situation of the healthcare professional: Active, Inactive, Retired</inlineHelpText>
        <label>IMS Ind. State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                    <isActive>false</isActive>
                    <label>Closed</label>
                </value>
                <value>
                    <fullName>Deceased</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Is opening</fullName>
                    <isActive>false</isActive>
                    <label>Is opening</label>
                </value>
                <value>
                    <fullName>Maternity/Paternity Leave</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                    <isActive>false</isActive>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Reduced Activity</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
                <value>
                    <fullName>Temporarily Closed</fullName>
                    <isActive>false</isActive>
                    <label>Temporarily Closed</label>
                </value>
                <value>
                    <fullName>Temporarily Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DP_IND_STATUS__c</fullName>
        <description>Controlling field for Ind State</description>
        <inlineHelpText>Status of the Individual (Contact) as provided by IMS</inlineHelpText>
        <label>IMS Ind. Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Provisional</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/dm_encodeTriggersTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class dm_encodeTriggersTest {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        Lead newLead = new Lead();
        newLead.FirstName = 'Mal';
        newLead.lastName = 'Reynolds';
        newLead.Company = 'Serenity Inc';
        insert newLead;
        system.assert(newLead.id != null, 'Insert didnt take, no id found');
        newLead.firstName = 'Captain Mal';
        newLead.Lastname = 'Freakin Reynolds';
        newLead.company = 'Firefly';
        update newLead;
        
        
        Account newAcct = new Account(); // Modified by - Akshay 12/02/2016
        newAcct.name = 'Serenity Inc';
        newAcct.BST_Country__c = 'Belgium';
        newAcct.RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('IMS Account').getRecordTypeId(); 
        newAcct.billingStreet = 'Test 123'; 
        newAcct.billingState = 'Test State';
        newAcct.billingCountry = 'Test Country';
        newAcct.billingCity = 'Test City';
        newAcct.billingPostalCode = '1111';
        insert newAcct;
        system.assert(newLead.id != null, 'Insert didnt take, no id found');
        newAcct.name = 'Firefly';
        update newAcct;
        
        
        Contact newCnct = new Contact();  // Modified by - Akshay 12/02/2016
        newCnct.Salutation = 'Mr.';
        newCnct.FirstName = 'Mal';
        newCnct.lastName = 'Reynolds';
        newCnct.accountid = newAcct.id;
        newCnct.RecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('IMS Contact').getRecordTypeId();
        newCnct.DP_IND_GENDER__c = 'Male';
        newCnct.DP_IND_STATUS__c = 'Valid';
        newCnct.DP_IND_STATE__c = 'Active';
        newCnct.DP_IND_PROFESSIONAL_TYPE__c = 'Nurse'; 
        newCnct.DP_IND_SPEC_1__c = 'Student';
        newCnct.BST_COUNTRY__c = 'Belgium';
        insert newCnct;
        system.assert(newLead.id != null, 'Insert didnt take, no id found');
        newCnct.Firstname = 'Captain Mal';
        newCnct.Lastname = 'Freakin Reynolds';
        update newCnct;
        
    }
}