src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_BAX_SALES_TEAM__c</fullName>
        <description>BST – Field to define the main Baxter team/Franchise for the user</description>
        <label>Baxter Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bax Company/Services</fullName>
                </value>
                <value>
                    <fullName>HC - Anesthesia/Critical Care</fullName>
                </value>
                <value>
                    <fullName>HC - BioSurgery</fullName>
                </value>
                <value>
                    <fullName>HC - Glob.Pharma Injectables</fullName>
                </value>
                <value>
                    <fullName>HC - Infusion Systems</fullName>
                </value>
                <value>
                    <fullName>HC - IV Therapies/SVP</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition Pediatrics</fullName>
                </value>
                <value>
                    <fullName>HC - Pharmacy Services</fullName>
                </value>
                <value>
                    <fullName>HC - Productivity Sys</fullName>
                    <isActive>false</isActive>
                    <label>HC - Productivity Sys</label>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                    <isActive>false</isActive>
                    <label>Market Access</label>
                </value>
                <value>
                    <fullName>MSL/Medical</fullName>
                    <isActive>false</isActive>
                    <label>MSL/Medical</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RE - Acute</fullName>
                </value>
                <value>
                    <fullName>RE - Hemo Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Peritoneal Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Water Treatment</fullName>
                </value>
                <value>
                    <fullName>Small Volume Parenterals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>BST_Account_Name__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_Contact_Name__c</fullName>
        <formula>Contact.FirstName &amp;&quot; &quot;&amp; Contact.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Contact.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the User.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_MAIN_BAXTER_TEAM__c</fullName>
        <description>BST – Field to define the main Baxter team for the user</description>
        <label>Main Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Bax Company/Services</fullName>
                </value>
                <value>
                    <fullName>HC - Anesthesia/Critical Care</fullName>
                </value>
                <value>
                    <fullName>HC - BioSurgery</fullName>
                </value>
                <value>
                    <fullName>HC - Glob.Pharma Injectables</fullName>
                </value>
                <value>
                    <fullName>HC - Infusion Systems</fullName>
                </value>
                <value>
                    <fullName>HC - IV Therapies/SVP</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition</fullName>
                </value>
                <value>
                    <fullName>HC - Pharmacy Services</fullName>
                </value>
                <value>
                    <fullName>RE - Acute</fullName>
                </value>
                <value>
                    <fullName>RE - Hemo Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Peritoneal Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Water Treatment</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition Pediatrics</fullName>
                </value>
                <value>
                    <fullName>Small Volume Parenterals</fullName>
                </value>
                <value>
                    <fullName>HC - Productivity Sys</fullName>
                    <isActive>false</isActive>
                    <label>HC - Productivity Sys</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_SECONDARY_COUNTRY__c</fullName>
        <description>Field to track the secondary country of the User.</description>
        <label>Secondary Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClsEventLightningController.cls
public with sharing class ClsEventLightningController {

    @AuraEnabled
    public static Contact getContact(Id contactId) {
        // Perform isAccessible() checks here
        return [SELECT FirstName, LastName FROM Contact WHERE Id = :contactId];
    } 
    @AuraEnabled
    public static dateTime getEndDateTime(dateTime startDate) {
        // To add one hour to start date - 13/10/17(KP)
        startDate = startDate.addHours(1);
        system.debug('startDate' +startDate);
        return startDate;
    } 
    @AuraEnabled
    public static Account getAccount(Id accountId) {
        // Perform isAccessible() checks here
        return [SELECT Name FROM Account WHERE Id = :accountId];
    }
    @AuraEnabled
    public static AccountContactRelation getAccConRel(Id relationId){
        return [SELECT AccountId, ContactId, BST_Account_Name__c, BST_Contact_Name__c FROM AccountContactRelation WHERE Id =:relationId];
    }
    @AuraEnabled
    public static String getUserCountry()
    {
        String Country = [Select Id, BST_COUNTRY__c FROM User where Id = :UserInfo.getUserId()].BST_COUNTRY__c;
        
        return Country;
    }
    
    @AuraEnabled
    public static String getProfileId() 
    {
        return userinfo.getProfileId();
    }
    
    @AuraEnabled
    public static Id getRecordTypeId(String objApiName, String recordTypeLabel)
    {
        return ClsApexUtil.getRecordTypeBySObject(objApiName).get(recordTypeLabel).getRecordTypeId();
    }

    @AuraEnabled
    public static Boolean getUserInfo()
    {
        Boolean isSecondaryEmpty = false;
        
        String Country = [Select Id, BST_COUNTRY__c, BST_SECONDARY_COUNTRY__c FROM User where Id = :UserInfo.getUserId()].BST_SECONDARY_COUNTRY__c;
        System.debug('###country: ' + country);
        if (Country == null)
            isSecondaryEmpty = true;
        
        return isSecondaryEmpty;
    }
    @AuraEnabled
    public static String getUserMPC()
    {
        List<User> country = [Select Id, BST_MAIN_BAXTER_TEAM__c FROM User where Id = :UserInfo.getUserId()];
        if(country[0].BST_MAIN_BAXTER_TEAM__c == null) {
            return '';
        }   
        else
            return country[0].BST_MAIN_BAXTER_TEAM__c;
    }
    @AuraEnabled
    public static List<String> getCountryValues(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Contact.BST_COUNTRY__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        options.sort();
        return options;
    }
    @AuraEnabled
    public static Event saveEventWithContact(Event evt, Id contactId, Id accountId,id BSTAssociatedCriticalMetricsID) {
        // Perform isAccessible() and isUpdateable() checks here
        //system.debug('entered the server side controller');
        Event newEvt = evt;
        newEvt.whatId = accountId;
        newEvt.whoId = contactId;
        newEvt.BST_Associated_Critical_Metrics__c =BSTAssociatedCriticalMetricsID;
        //Below lines of code will convert the translated value
        evt.BST_CALL_TYPE__C = ClsApexUtil.picklistLableValueMap('BST_CALL_TYPE__C').get(evt.BST_CALL_TYPE__C);
        evt.BST_BAX_SALES_TEAM__C = ClsApexUtil.picklistLableValueMap('BST_BAX_SALES_TEAM__C').get(evt.BST_BAX_SALES_TEAM__C);
        evt.BST_MAIN_TOPIC__C = ClsApexUtil.picklistLableValueMap('BST_MAIN_TOPIC__C').get(evt.BST_MAIN_TOPIC__C);
        try
        {
            insert newEvt;
        }catch(DmlException e){
            String errMsg = e.getDmlMessage(0);
            if (errMsg.equalsIgnoreCase('Related To Is Required'))
                errMsg = 'Account Name is Required';
            else if (errMsg.equalsIgnoreCase('Name Is Required'))
                errMsg = 'Contact Name is Required';
            throw new AuraHandledException(errMsg);
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }    
        return newEvt;
    } 

    @AuraEnabled
    public static List<String> getEventTypeValues(String recdType)
    {
       
        List<String> possibleEventTypeValues = new List<String>();
        possibleEventTypeValues.add('');
        Schema.DescribeFieldResult fieldResult = Event.BST_CALL_TYPE__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        Set<String> checkRecdTypePossibleValues = ClsApexUtil.getPossibleLOVs(recdType, 'BST_CALL_TYPE__c');
            
        for( Schema.PicklistEntry field : ple)
        {
            if(checkRecdTypePossibleValues.contains(field.getLabel())) 
            {
                   possibleEventTypeValues.add(field.getLabel());
            }
        }  
        possibleEventTypeValues.sort();    
        return possibleEventTypeValues;
    }   
        
    @AuraEnabled
    public static List<String> getMainProductCategoryValues(String recdType, String country)
    {
       List<String> possibleProductCategoryValues = new List<String>();
       possibleProductCategoryValues.add('');
       PicklistFieldController controller = new PicklistFieldController();
       Map<String,List<String>> valueMap = controller.getDependentOptionsImpl('Event','BST_COUNTRY__c','BST_BAX_SALES_TEAM__c');
       //Set<String> checkRecdTypePossibleValues = ClsApexUtil.getPossibleLOVs(recdType, 'BST_BAX_SALES_TEAM__c');
       if(!valueMap.get(country).isEmpty())
       {
           for(String val : valueMap.get(country))
           {
               //if(checkRecdTypePossibleValues.contains(val)) {
                   possibleProductCategoryValues.add(val);
               //}
           }
       }
       possibleProductCategoryValues.sort(); 
       return  possibleProductCategoryValues;
    }
    
    @AuraEnabled
    public static List<String> getMainTopicValues(String recdType, String mainProductCategory)
    {
       List<String> possibleTopicValues = new List<String>();
       possibleTopicValues.add('');
       PicklistFieldController controller = new PicklistFieldController();
       Map<String,List<String>> valueMap = controller.getDependentOptionsImpl('Event','BST_BAX_SALES_TEAM__c','BST_MAIN_TOPIC__c');
       //Set<String> checkRecdTypePossibleValues = ClsApexUtil.getPossibleLOVs(recdType, 'BST_MAIN_TOPIC__c');
       if(!valueMap.get(mainProductCategory).isEmpty())
       {
           for(String val : valueMap.get(mainProductCategory))
           {
               //if(checkRecdTypePossibleValues.contains(val)) {
                   possibleTopicValues.add(val);
               //}
           }
       }
       possibleTopicValues.sort();
       return  possibleTopicValues;
    }
    
    @AuraEnabled
    public static List<String> getEventRecordTypes(){
        List<String> retRecordTypeList = new List<String>();
        retRecordTypeList.add('');
        List<Schema.RecordTypeInfo> recdTypeInfoList = Event.SObjectType.getDescribe().getRecordTypeInfos();
        if (recdTypeInfoList.size() > 1)
        {
            for (RecordTypeInfo recdType : recdTypeInfoList) 
            {
                if (recdType.isAvailable() && !String.valueOf(recdType.getRecordTypeId()).endsWith('AAA'))
                   retRecordTypeList.add(recdType.getName());
            }        
        }
        return retRecordTypeList;
    }
    @AuraEnabled
    public static List<Contact> getAssociatedContacts(Id contactId)
    {
        Set<Id> conIds = new Set<Id>();
        List<AccountContactRelation> acccRelLst = [SELECT ContactId FROM AccountContactRelation WHERE ContactId = : contactId];
        for(AccountContactRelation accRel : acccRelLst)
            conIds.add(accRel.ContactId);
        List<Contact> conLst = [SELECT Id, Name FROM Contact where Id IN : conIds];
        return conLst;
    }

    @AuraEnabled
    public static Profile getUserProfile() 
    {
    Profile p = [Select Name from Profile where Id =: userinfo.getProfileid()];
    return p; 
    }

    @AuraEnabled
    public static String getDefaultEventTypeValue (String recdType)
    {
        String defaultValue;
        Set<String> valSet = new Set<String>();
        valSet = ClsAPexUtil.getPossibleLOVs(recdType, 'BST_BAX_SALES_TEAM__c');
        if (!valSet.isEmpty())
            defaultValue = (new list<string>(valSet) )[0] ;
        else
            defaultValue = 'NODEFAULTVALUE';    
        return defaultValue;
    }
 
//Invocable method to be used in flow to check if object has feed  tracking enabled-13/10/17(KP)
    @InvocableMethod
   public static list<boolean> getChatterUpdate(list<id> currId) {
       list<Boolean> isChatter = new list<Boolean>();
       id selId = currId[0];
       String sObjName = selId.getSObjectType().getDescribe().getName();
       Schema.SObjectType objToken = Schema.getGlobalDescribe().get(sObjName);
       Schema.DescribeSObjectResult drSObj = objToken.getDescribe();
       boolean hasChatter = drSObj.isFeedEnabled(); 
       isChatter.add(hasChatter);
       return isChatter;
   }
    
}