src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_BAX_SALES_TEAM__c</fullName>
        <description>BST – Field to define the main Baxter team/Franchise for the user</description>
        <label>Baxter Team</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Bax Company/Services</fullName>
                </value>
                <value>
                    <fullName>HC - Anesthesia/Critical Care</fullName>
                </value>
                <value>
                    <fullName>HC - BioSurgery</fullName>
                </value>
                <value>
                    <fullName>HC - Glob.Pharma Injectables</fullName>
                </value>
                <value>
                    <fullName>HC - Infusion Systems</fullName>
                </value>
                <value>
                    <fullName>HC - IV Therapies/SVP</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition</fullName>
                </value>
                <value>
                    <fullName>HC - Nutrition Pediatrics</fullName>
                </value>
                <value>
                    <fullName>HC - Pharmacy Services</fullName>
                </value>
                <value>
                    <fullName>HC - Productivity Sys</fullName>
                    <isActive>false</isActive>
                    <label>HC - Productivity Sys</label>
                </value>
                <value>
                    <fullName>Market Access</fullName>
                    <isActive>false</isActive>
                    <label>Market Access</label>
                </value>
                <value>
                    <fullName>MSL/Medical</fullName>
                    <isActive>false</isActive>
                    <label>MSL/Medical</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>RE - Acute</fullName>
                </value>
                <value>
                    <fullName>RE - Hemo Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Peritoneal Dialysis</fullName>
                </value>
                <value>
                    <fullName>RE - Water Treatment</fullName>
                </value>
                <value>
                    <fullName>Small Volume Parenterals</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/INTEGRATION_LOG__c.object
<CustomObject>
    <description>Custom object used for IMS approval process for objects Account, Contact, AccountContactRelationShip, Account_Account_Relation__c</description>
    <fields>
        <fullName>BST_ACCOUNT_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id to track changes made for the Account</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>IMS Integration Logs</relationshipLabel>
        <relationshipName>IMS_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Approved</fullName>
                    <isActive>false</isActive>
                    <label>Baxter Approved</label>
                </value>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Approved</fullName>
                    <isActive>false</isActive>
                    <label>IMS Approved</label>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_TYPE__c</fullName>
        <description>Stores the information of the object whether it&apos;s updated or created for which the integration log has been created.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>AccountAccountRelation Create</fullName>
                </value>
                <value>
                    <fullName>AccountAccountRelation Update</fullName>
                </value>
                <value>
                    <fullName>AccountContactRelation Create</fullName>
                </value>
                <value>
                    <fullName>AccountContactRelation Update</fullName>
                </value>
                <value>
                    <fullName>Account Create</fullName>
                </value>
                <value>
                    <fullName>Account Update</fullName>
                </value>
                <value>
                    <fullName>Contact Create</fullName>
                </value>
                <value>
                    <fullName>Contact Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>IMS Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000}</displayFormat>
        <label>BOOST Integration Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the User.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TgrIntegrationLogTrigger_Test.cls
//Akshay 11/23/2016
//Description: - This class will be used for test coverage of TgrIntegrationLogTrigger trigger on Integration Log.

@isTest
public class TgrIntegrationLogTrigger_Test{

      /* Test method to check approval process on object Integration Log. */
      static testMethod void testINTEGRATION_LOGNonAdminInsert(){
          test.starttest();
          User u = ClsTestDataUtility.createuser('Belgium','Belgium');
          Account acc = ClsTestDataUtility.createAccount('Belgium');
        
          System.runAs(u) {
              Schema.DescribeSObjectResult d = Schema.SObjectType.Account;
              Map<String,Schema.RecordTypeInfo> rtMapByName = d.getRecordTypeInfosByName();
              Schema.RecordTypeInfo rtByName =  rtMapByName.get('IMS Account');
              acc.recordtypeid=rtByName.getRecordTypeId();
              insert acc;
              //List<INTEGRATION_LOG__c> iList = [select id, name,BST_ACCOUNT_ID__c from INTEGRATION_LOG__c WHERE BST_ACCOUNT_ID__c =:acc.id limit 1];
              //system.assertEquals(acc.Id,iList[0].BST_ACCOUNT_ID__c,'Error');
          }
 
          INTEGRATION_LOG__c iLog= new INTEGRATION_LOG__c();
          iLog = [select id, BST_Country__c from INTEGRATION_LOG__c where BST_ACCOUNT_ID__c =:acc.id limit 1];
          ilog.BST_STATUS__c='Baxter Rejected';
          iLog.BST_TYPE__c='Account Update';  
          update iLog;
          //system.assertEquals(acc.BST_Country__c,iLog.BST_Country__c,'Error');
          
          test.stopTest();
     }
     static testMethod void testEventDetailsMDT(){
         test.startTest();
         INTEGRATION_LOG__c iLog= ClsTestDataUtility.createINTEGRATION_LOG();
         insert iLog;
         ClsApexUtil.getPossibleLOVs('Field Customer Call','BST_BAX_SALES_TEAM__c');
         ClsApexUtil.getWorkItemId(iLog.Id);
         ClsApexUtil.rejectRecord(iLog,'Rejected');
         test.stopTest();
     }
}