src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Record_Types__mdt.object
<CustomObject>
    <description>Record_Types Developer Names.</description>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <description>Developer_Name.</description>
        <inlineHelpText>Developer_Name.</inlineHelpText>
        <label>Developer_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Record_Types</label>
    <pluralLabel>Record_Types</pluralLabel>
</CustomObject>

src/classes/TRY_Lightning_Competitors_Controller.cls
public with sharing class TRY_Lightning_Competitors_Controller {

@AuraEnabled    
      public static List<Account> getCompetitors() {
      
      try{
      Record_Types__mdt AccountCompetitorRT_MDT =  [SELECT Id, MasterLabel, Developer_Name__c
                 FROM Record_Types__mdt
                 where MasterLabel = 'Competitor'];
      
      if(AccountCompetitorRT_MDT !=null){    
      system.debug('##################################################### YB AccountCompetitorRT_MDT' + AccountCompetitorRT_MDT);    
      }         
      
      RecordType accountCompetitorRT =  [SELECT Id, Name
                 FROM RecordType
                 where DeveloperName =: AccountCompetitorRT_MDT.Developer_Name__c];
      
      if(accountCompetitorRT !=null){    
      system.debug('##################################################### YB accountCompetitorRT' + accountCompetitorRT);    
      }         
                 
      List<Account> competitors = 
                [SELECT Id, Name, RecordTypeId
                 FROM Account
                 where RecordTypeId =: accountCompetitorRT.Id];
      
      if(competitors !=null){    
      system.debug('##################################################### YB competitors' + competitors);    
      }         
                
                 //AND 
                 //ADD SPECIFIC CRITERIA HERE
                
        //Add isAccessible() check
        return competitors;
      }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
            + e.getMessage());    
        }
        
    }

@AuraEnabled    
    public static List<Account> serverGetCompetitorsByCountry(string serverCountryNameValue) {
      
      List<Account> competitors = new List<Account>();
      system.debug('##################################################### YB getCompetitors(country)');    
      
      try{
      Record_Types__mdt AccountCompetitorRT_MDT =  [SELECT Id, MasterLabel, Developer_Name__c
                 FROM Record_Types__mdt
                 where MasterLabel = 'Competitor'];
      
      if(AccountCompetitorRT_MDT !=null){    
      system.debug('##################################################### YB AccountCompetitorRT_MDT' + AccountCompetitorRT_MDT);    
      }         
      
      RecordType accountCompetitorRT =  [SELECT Id, Name
                 FROM RecordType
                 where DeveloperName =: AccountCompetitorRT_MDT.Developer_Name__c];
      
      if(accountCompetitorRT !=null && serverCountryNameValue !=null){
      system.debug('##################################################### YB accountCompetitorRT' + accountCompetitorRT);    
      system.debug('##################################################### YB serverCountryNameValue' + serverCountryNameValue);    
               
      competitors = 
                [SELECT Id, Name, RecordTypeId, BST_COUNTRY__c
                 FROM Account
                 where RecordTypeId =: accountCompetitorRT.Id and BST_COUNTRY__c =: serverCountryNameValue];
      
      if(competitors !=null){    
      system.debug('##################################################### YB competitors' + competitors);    
      }         
                
                 //AND 
                 //ADD SPECIFIC CRITERIA HERE
                
        //Add isAccessible() check
        
      }
      return competitors;
      }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
            + e.getMessage());    
        }
        
    }
}