src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>BST_IMS_Account</fullName>
        <active>true</active>
        <description>Used for details about Health Care Entities (hospitals, departments, etc.), as contracted with your data provider. Creating or updating these records initiates the approval process to your Country Admin, and validation with data provider when appropriate</description>
        <label>IMS Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>BST_Country__c</fullName>
        <description>BST - Field to track the country.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BST_Country</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Contact.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>For Marking the record with different status.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baxter Pending Review</fullName>
                </value>
                <value>
                    <fullName>Baxter Rejected</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                    <isActive>false</isActive>
                    <label>Completed</label>
                </value>
                <value>
                    <fullName>IMS Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Partially Accepted</fullName>
                </value>
                <value>
                    <fullName>IMS Pending Review</fullName>
                </value>
                <value>
                    <fullName>IMS Rejected</fullName>
                </value>
                <value>
                    <fullName>IMS Updated</fullName>
                    <isActive>false</isActive>
                    <label>IMS Updated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>The value is fetched from Global Value Set BST_COUNTRY_GLOBAL. This field is used in visibility fielters for My Profile/All profile views and also this is used in sharing rules so that the users can see the correct set of questions based on the country/countries they cover</description>
        <inlineHelpText>The country where the question needs to be visible</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BST_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_PROFILE_TYPE__c</fullName>
        <description>BST - picklist set on gloabl question and used on the lookup filter from child, so that Account Question record type can be linked only to Account Parent types and Contact question record type can be linked only to Contact Parent questions</description>
        <inlineHelpText>Value set on Global Questions (Parent Questions) in order to allow only childs of the correct type to be linked to parents (Account Question record type linked to Account Parent; Contact Question Record Type linked to Contact Parent)</inlineHelpText>
        <label>Profile Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>BST - Status of the question. Drive visibility in My Profile/All profile since only active questions are shown on there. Inactive questions can be reported on. Automatic logic based on Start Date/End date to automatically change the status of a question to Active/Inactive based on the current date compared to Start and End Dates</description>
        <inlineHelpText>Status of the question drives visibility in My Profile/All Profile. Only active questions are shown to users for data insert. Inactive questions can be reported on but will not be shown for data gathering</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>BST_Global_Question</fullName>
        <active>true</active>
        <description>Used as a parent question</description>
        <label>Global Question</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClsLookupSObjectController.cls
/********************************************************************************
Apex Class Name - ClsLookupSObjectController
Version - 1.0
Created Date - Nov 3, 2016
Function - Apex Class for getting the search result on the basis 
           of the name in sObject Specify by the calling function
           
           

Modification Log : 
--------------------------------------------------------------------------------

* Developer               Date                 Description
* -------------------     ------------         -----------------------
* Gaurav Jain             11/4/2016           Original Version
* Arpit Agarwal           06/09/2017          Change for Question Epic
* Arpit Agarwal			  08/22/2017 		  Change for BOOS-240	 
********************************************************************************/

public with sharing class ClsLookupSObjectController {
    
    /**
     * Function Name: lookup
     * Purpose: Aura enabled method to search a specified SObject for a specific string
     * 
     * @param searchString :    string conatins value to be search against name field
     * @param sObjectAPIName:   string contains sObject Api Name
     * 
     * Return Type: List<LookupSObjectController.Result>     
     * 
     */    
    @AuraEnabled
    public static List<ClsLookupSObjectController.Result> lookup(String searchString, String sObjectAPIName, String recordTypeName, String fieldsToDisplay, String currRecord, Boolean isForBUProfiling)
    {
        List<ClsLookupSObjectController.Result> results = new List<Result>();
        
         system.debug('recordTypeName'+recordTypeName);     
        String searchQuery;
        
        //Check if search or sObjectAPIName string is blank or null
        if(String.isBlank(searchString) && String.isBlank(sObjectAPIName))
            return results;
        
        // Sanitze the input  
        String sanitizedSearchString = String.escapeSingleQuotes(searchString);
        String sanitizedSObjectAPIName = String.escapeSingleQuotes(sObjectAPIName);
        String sanitizedFieldNames;
        List<String> sanitizedFieldsList;
        
        if(fieldsToDisplay != null) {
            sanitizedFieldNames = String.escapeSingleQuotes(fieldsToDisplay);
            sanitizedFieldsList = sanitizedFieldNames.split(',');
            String blank = '';
            while(sanitizedFieldsList.size() < 3) {
                sanitizedFieldsList.add(blank);
            }
            
        }
            
        else {
            sanitizedFieldNames = 'Name';
            
        }
        
        Set<Id> recordIds = new Set<Id>();
        if(sObjectAPIName == 'Account') 
        {
            if(isForBUProfiling == true)
            {   String namesearch= '%'+searchString+'%';
                List<Account> acr = [SELECT Id FROM Account where RecordType.DeveloperName IN ('BST_IMS_Account') and Name like :namesearch];         
                for(Account a : acr)
                {
                recordIds.add(a.Id);
                }
            } else
            {
                System.debug('###filtering by account');
                List<AccountContactRelation> acr = [SELECT AccountId FROM AccountContactRelation where ContactId = :currRecord];
                
                for(AccountContactRelation a : acr) 
                    {
                    recordIds.add(a.AccountId);
                    }
            }
        }
        
        if(sObjectAPIName == 'Question__c') {           
          List<Question__c> ques = new List<Question__c>();
		  if(recordTypeName == 'Account Profile Question'){		  
			  ques = [SELECT Id FROM Question__c where BST_Status__c =:'Active' and RecordType.DeveloperName = :'BST_Global_Question' and BST_PROFILE_TYPE__c = :'Account'];
		  }	   
		  else if(recordTypeName == 'Contact Profile Question'){
			  ques = [SELECT Id FROM Question__c where BST_Status__c =:'Active' and RecordType.DeveloperName = :'BST_Global_Question' and BST_PROFILE_TYPE__c = :'Contact'];
		  }	  
			  System.debug('The values are :' +ques);
			  for(Question__c q : ques) {
				recordIds.add(q.Id);
          }
        }
        
        if(sObjectAPIName == 'Contact') {
            System.debug('###filtering by contact');
            List<AccountContactRelation> acr = [SELECT ContactId FROM AccountContactRelation where AccountId = :currRecord];
            
            for(AccountContactRelation a : acr) {
                recordIds.add(a.ContactId);
            }
        }
        
         //Adding Code for campaign
         if(sObjectAPIName == 'Campaign') {
          System.debug('###filtering by Campaign');
           List<Campaign> acr = [SELECT id FROM Campaign where BST_Country__c = :currRecord and IsActive = True and (Type =:system.label.BST_Type_Event or Type =:system.label.BST_Type_Opportunity) and (RecordType.Name =:system.label.BST_RecordType_Lead_Metrics or RecordType.Name =:system.label.BST_RecordType_Lag_Metrics)];          
             
          for(Campaign a : acr) {
            recordIds.add(a.id);
          }
        }
        
        if(sObjectAPIName == 'Account' || sObjectAPIName == 'Contact')
        // Build our SOSL query
        searchQuery = 'FIND \'' + sanitizedSearchString + '*\' IN All FIELDS RETURNING ' + sanitizedSObjectAPIName + '(Id,' + sanitizedFieldNames + ' WHERE Id IN :recordIds) Limit 5';         
         else
            searchQuery = 'FIND \'' + sanitizedSearchString + '*\' IN All FIELDS RETURNING ' + sanitizedSObjectAPIName + '(Id,' + sanitizedFieldNames + ' WHERE Id IN :recordIds) Limit 5';         

        
        system.debug('searchQuery is ' + searchQuery);
        // Execute the Query
        List<List<SObject>> searchList = search.query(searchQuery);
                     
        // Create a list of matches to return
        for (SObject so : searchList[0])
        {
            if(sanitizedFieldsList[1] == '' && sanitizedFieldsList[2] != '')
                results.add(new Result((String)so.get(sanitizedFieldsList[0]), so.Id, null, null, (String)so.get(sanitizedFieldsList[2]), sanitizedFieldsList[2], sObjectAPIName));
            
            if(sanitizedFieldsList[2] == '' && sanitizedFieldsList[1] != '')
                results.add(new Result((String)so.get(sanitizedFieldsList[0]), so.Id, (String)so.get(sanitizedFieldsList[1]), sanitizedFieldsList[1], null, null, sObjectAPIName));
            
            if(sanitizedFieldsList[1] == '' && sanitizedFieldsList[2] == '')
                results.add(new Result((String)so.get(sanitizedFieldsList[0]), so.Id, null, null, null, null, sObjectAPIName));
                
            if(sanitizedFieldsList[1] != '' && sanitizedFieldsList[2] != '')
                results.add(new Result((String)so.get(sanitizedFieldsList[0]), so.Id, (String)so.get(sanitizedFieldsList[1]), sanitizedFieldsList[1], (String)so.get(sanitizedFieldsList[2]), sanitizedFieldsList[2], sObjectAPIName));
            
        }
        return results;
        
    }
    
    /**
     * Inner class to wrap up an SObject Label and its Id
     */
    public class Result
    {
        @AuraEnabled public String SObjectLabel;
        @AuraEnabled public Id SObjectId;
        @AuraEnabled public String sObjectExtraField1;
        @AuraEnabled public String sObjectExtraField1Label;
        @AuraEnabled public String sObjectExtraField2;
        @AuraEnabled public String sObjectExtraField2Label;
        @AuraEnabled public String sObjectAPIName;
         
        public Result(String sObjectLabel, Id sObjectId, String sObjectExtraField1, String sObjectExtraField1Label, String sObjectExtraField2, String sObjectExtraField2Label, String sObjectAPIName)
        {
            this.SObjectLabel = sObjectLabel;
            this.SObjectId = sObjectId;
            this.sObjectAPIName = sObjectAPIName;
            this.sObjectExtraField1 = sObjectExtraField1;
            this.sObjectExtraField2 = sObjectExtraField2;
            
            if(sObjectExtraField1Label != null)
                this.sObjectExtraField1Label = Schema.getGlobalDescribe().get(sObjectAPIName).getDescribe().fields.getMap().get(sObjectExtraField1Label).getDescribe().getLabel();
            
            if(sObjectExtraField2Label != null)
                this.sObjectExtraField2Label = Schema.getGlobalDescribe().get(sObjectAPIName).getDescribe().fields.getMap().get(sObjectExtraField2Label).getDescribe().getLabel();
        }
    }
}