src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Account.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Germany</fullName>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Account_Profile__c.object
<CustomObject>
    <label>Account Profile</label>
    <nameField>
        <displayFormat>AP-{00000000}</displayFormat>
        <label>Account Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BST_Global_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Global Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the Contact.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Global_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global settings to create and manage custom data for this organization</description>
    <label>Global Settings</label>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <fields>
        <fullName>BST_CATEGORY__c</fullName>
        <description>The pick list is dependent on Major Category pick-list. This field can be used to group questions into logical streams and is used for grouping into My Profile/all Profile screens under Account and Contact</description>
        <inlineHelpText>Field dependent on selection made in Major Category. The value allows logical grouping of the questions</inlineHelpText>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_MAJOR_CATEGORY__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Competitive information</fullName>
                </value>
                <value>
                    <fullName>CRRT Baxter Insight</fullName>
                </value>
                <value>
                    <fullName>CRRT Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>General Account information</fullName>
                </value>
                <value>
                    <fullName>HD Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>PD Baxter Insight</fullName>
                </value>
                <value>
                    <fullName>PD Competitive Insight</fullName>
                </value>
                <value>
                    <fullName>Vial-Mate, Frozen, Vanco Dex</fullName>
                </value>
                <value>
                    <fullName>Gas</fullName>
                </value>
                <value>
                    <fullName>Baxter Data</fullName>
                </value>
                <value>
                    <fullName>Hospital Potential</fullName>
                </value>
                <value>
                    <fullName>Profiling</fullName>
                </value>
                <value>
                    <fullName>Clinical Studies</fullName>
                </value>
                <value>
                    <fullName>Home Based Hemodialysis Therapies</fullName>
                </value>
                <value>
                    <fullName>Key Metrics</fullName>
                </value>
                <value>
                    <fullName>Unit Assessment</fullName>
                </value>
                <value>
                    <fullName>Treatment Criteria</fullName>
                </value>
                <value>
                    <fullName>Delivered CRRT Dose</fullName>
                </value>
                <value>
                    <fullName>Fluid Overload</fullName>
                </value>
                <value>
                    <fullName>Recirculation</fullName>
                </value>
                <value>
                    <fullName>SLED Threat</fullName>
                </value>
                <value>
                    <fullName>Common Settings</fullName>
                </value>
                <value>
                    <fullName>Anticoagulation</fullName>
                </value>
                <value>
                    <fullName>Additional Information</fullName>
                </value>
                <value>
                    <fullName>Unit Specific Information</fullName>
                </value>
                <value>
                    <fullName>Short Term Catheter</fullName>
                </value>
                <value>
                    <fullName>Prismaflex Custom Mode</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>The value is fetched from Global Value Set BST_COUNTRY_GLOBAL. This field is used in visibility fielters for My Profile/All profile views and also this is used in sharing rules so that the users can see the correct set of questions based on the country/countries they cover</description>
        <inlineHelpText>The country where the question needs to be visible</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BST_Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_MAJOR_CATEGORY__c</fullName>
        <description>BST - pick list dependent on Country. Used to allow grouping of questions into logical buckets</description>
        <inlineHelpText>Pick list used to group questions in logical segments. The grouping will be done into My Profile/All Profile</inlineHelpText>
        <label>Major Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CRRT</fullName>
                </value>
                <value>
                    <fullName>Surgery</fullName>
                </value>
                <value>
                    <fullName>Anesthesia</fullName>
                </value>
                <value>
                    <fullName>Renal</fullName>
                </value>
                <value>
                    <fullName>Advanced Surgery</fullName>
                </value>
                <value>
                    <fullName>Medical Affairs (MSL)</fullName>
                </value>
                <value>
                    <fullName>Renal Chronic Census</fullName>
                </value>
                <value>
                    <fullName>HP - Fluid Systems</fullName>
                </value>
                <value>
                    <fullName>Nurse Worksheet</fullName>
                </value>
                <value>
                    <fullName>Anestetics</fullName>
                    <isActive>false</isActive>
                    <label>Anestetics</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BST_SALESFORCE_GROUP__c</fullName>
        <description>BST - this multipicklist is used for visibility filter in My profile sections on Accounts and Contacts. Based on the selections made here and the groups membership set on user level, the question is available or not to the user in My Profile section</description>
        <inlineHelpText>2 or 3 letters acronyms that define the Franchises or user groups in countries. The values selected will make the question editable only by users that are part of at least one of the selected groups</inlineHelpText>
        <label>Baxter User Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>BST_COUNTRY__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>HD</fullName>
                </value>
                <value>
                    <fullName>PD</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>MSL</fullName>
                </value>
                <value>
                    <fullName>Hospital Products</fullName>
                </value>
                <value>
                    <fullName>Renal Chronic</fullName>
                </value>
                <value>
                    <fullName>Renal Acute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <recordTypes>
        <fullName>BST_ACCOUNT_PROFILE_QUESTION</fullName>
        <active>true</active>
        <description>Used for  Account Profile Functionality</description>
        <label>Account Profile Question</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_COUNTRY__c</fullName>
        <description>Field to track the country of the User.</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LtngCtrlSObjectAllProfile_Test.cls
/********************************************************************************
Apex Class Name - LtngCtrlSObjectAllProfile_Test
Version - 1.0
Created Date - Nov 3rd, 2016
Function - Test class for  LtngCtrlSObjectAllProfile 
 
Modification Log : 
--------------------------------------------------------------------------------
* Developer               Date                 Description
* -------------------     ------------         -----------------------
* Dharani Pothula         11/03/2016           Original Version
* Gaurav Jain             11/15/2016           To Include the test Coverage for the Contact Related Profiling
*Shashank Mehra           25/08/2017           To add methods to cover LtngCtrlSobjectAllProfile    
********************************************************************************/

@isTest
public class LtngCtrlSObjectAllProfile_Test {
    public static List<Question__c> quesList;
    public static List<Question__c> quesList1;
        
    public static testMethod void testGetCategoryOptions_ReturnStringList(){
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
        //Creating Questions
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
                       
     //   Related_Account__c relAcc = TestClassHelper.CreateRelatedAccount(TestClassHelper.accSList[1].id,TestClassHelper.accSList[0].id,'JDE - MII Facility');
        
    //    TestClassHelper.updateAccountWithMII(TestClassHelper.accSList[0], TestClassHelper.accSList[1]);
        
        /**
        *    Checking AccountProfileMyController if there is no Question in the system
        *   
        */
        System.RunAs(SysAdminUser){
            Test.startTest();
                List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
                CommonStringConverterUtilities.convertStringToDate(string.valueof(date.today()),'YYYY-MM-DDThh:mm:ss.mmm');
                CommonStringConverterUtilities.convertStringToNumber( '123' , '.####');
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.BST_ACCOUNT_PROFILE_PICKLIST_NONE);
        }
    }
    
    public static testMethod void testGetCategoryOptions_ReturnStringListWithQuestions(){
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
  //      Related_Account__c relAcc = TestClassHelper.CreateRelatedAccount(TestClassHelper.accSList[1].id,TestClassHelper.accSList[0].id,'JDE - MII Facility');
        
    //    TestClassHelper.updateAccountWithMII(TestClassHelper.accSList[0], TestClassHelper.accSList[1]);
            //creating  Questions records without category
        List<Question__c> accques1 = TestClassHelper.createQuestionRecsWOCat();
        List<Question__c> accques11 = TestClassHelper.CreateQuestionRecs();
        
        /**
        *    Checking AccountProfileMyController if there is no Question in the system
        *   
        */
        System.RunAs(SysAdminUser){
            Test.startTest();
            List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques11[0].BST_MAJOR_CATEGORY__c,accques11[0].BST_CATEGORY__c );
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.BST_ACCOUNT_PROFILE_PICKLIST_NONE);
        }
    }
    
    public static testMethod void testGetCategoryOptions_returnStringOfCategory_questionswithCategories(){
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
    //    Related_Account__c relAcc = TestClassHelper.CreateRelatedAccount(TestClassHelper.accSList[1].id,TestClassHelper.accSList[0].id,'JDE - MII Facility');
        
     //   TestClassHelper.updateAccountWithMII(TestClassHelper.accSList[0], TestClassHelper.accSList[1]);

        //creating  Questions records with category
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
        
        //creating  Account Profile records
     //   List<Account_Profile__c> accproff = TestClassHelper.CreateAccProfile(TestClassHelper.accSList[1].id,accques);
    //    update accproff;
        
        /**
        *    Checking AccountProfileMyController if there is no Question in the system
        *   
        */
        System.RunAs(SysAdminUser){
            Test.startTest();
            List<String> categoryList = LtngCtrlSObjectMyProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            List<String> subcategoryList = LtngCtrlSObjectMyProfile.getSubCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);   
            //  system.assert(categoryList.size() == 2);
            //    system.assertEquals('HD', categoryList[1]);
            
            List<AccountProfileWrapper> accProfWrp = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,categoryList[1],subcategoryList[1],true,true,'HD');
           accProfWrp.sort();
            Test.stopTest();
            system.assert(accProfWrp.size() == 0);
          
            
            //  AccountProfileQuestions.getQuestionsWithSavedResponses();
            
        }
    }
    
    public static testMethod void testSaveResponse_returnString(){
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
    //    Related_Account__c relAcc = TestClassHelper.CreateRelatedAccount(TestClassHelper.accSList[1].id,TestClassHelper.accSList[0].id,'JDE - MII Facility');
        
     //   TestClassHelper.updateAccountWithMII(TestClassHelper.accSList[0], TestClassHelper.accSList[1]);

        //creating  Questions records with category
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
        //creating  Account Profile records
        List<Account_Profile__c> accproff = TestClassHelper.CreateAccProfile(TestClassHelper.accSList[0].id,accques);     
        /**
        *    Checking AccountProfileMyController if there is no Question in the system
        *   
        */
        System.RunAs(SysAdminUser){
            Test.startTest();     
            List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            List<String> catlist = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            //system.assert(categoryList.size() == 2);
            //system.assertEquals('All', categoryList[0]);
                
            List<AccountProfileWrapper> accProfWrp = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,categoryList[0],'All',true,true ,'HD');
            List<AccountProfileWrapper> accProfWrp1 = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,catlist[0],'All',true,false,'HD');
            accProfWrp.sort();
            accProfWrp1.sort();
            Test.stopTest();
            system.assert(accProfWrp1.size()>0);   
            system.assert(accProfWrp.size() > 0);
            
           }
    }
    
    public static testMethod void testgetGroupOptionList ()
    {
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
        //Creating Questions
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
         //creating  Account Profile records
        List<Account_Profile__c> accproff = TestClassHelper.CreateAccProfile(TestClassHelper.accSList[0].id,accques);
        update accproff;
        System.RunAs(SysAdminUser){
            test.startTest(); 
            List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            List<String> groupList = LtngCtrlSObjectAllProfile.getGroupOptionList(TestClassHelper.accSList[0].id, 'Account',accques[0].BST_SALESFORCE_GROUP__c);
            List<AccountProfileWrapper> accProfWrp = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,categoryList[0],'All',true,true ,accques[0].BST_SALESFORCE_GROUP__c);
               
            accProfWrp.sort();
            test.stopTest();
            system.assert(accProfWrp.size() > 0);
        }
    }
    
    public static testMethod void testgetSubCategoryOptionList()
    {
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
        //Creating Questions
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
          //creating  Account Profile records
        List<Account_Profile__c> accproff = TestClassHelper.CreateAccProfile(TestClassHelper.accSList[0].id,accques);
        update accproff;
        System.RunAs(SysAdminUser)
        {
            List<String> subcategoryList = LtngCtrlSObjectAllProfile.getSubCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            List<AccountProfileWrapper> accProfWrp = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,subcategoryList[0],'All',true,true ,'HD');
            accProfWrp.sort();
            system.assert(accProfWrp.size() > 0);  
        }
    }
    
     public static testMethod void testgetSubCategoryOptionListElseloop()
    {
        test.startTest();
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'HD');
        //creating  Custom Settings
        List<sObject> ls = Test.loadData(BST_Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Accounts
        TestClassHelper.creatBulkAccount(10);
        //Creating Questions
        List<Question__c> accques = TestClassHelper.CreateQuestionRecs();
        System.RunAs(SysAdminUser)
        {
            List<String> subcategoryList = LtngCtrlSObjectAllProfile.getSubCategoryOptionList(TestClassHelper.accSList[0].id, 'Account',true,accques[0].BST_MAJOR_CATEGORY__c,accques[0].BST_CATEGORY__c);
            
            List<AccountProfileWrapper> accProfWrp = LtngCtrlSObjectAllProfile.getAccountIncrementCounter(TestClassHelper.accSList[0].id,'All',subcategoryList[0],true,false,'HD');
            accProfWrp.sort();
            system.assert(accProfWrp.size()==0);
            
                
        }
        
        test.stopTest();
    }
    
    public static testMethod void createQuestions(){
        
        quesList = TestClassHelper.createBioSurgQuestionRecs('BST_ACCOUNT_PROFILE_QUESTION');
        quesList1 = TestClassHelper.createBioSurgQuestionRecsWOCat('BST_ACCOUNT_PROFILE_QUESTION');
    }    

    
    public static testMethod void testgetAvailableReports(){
        
        List<Report> reportslist = LtngCtrlSObjectAllProfile.getAvailableReports();
        LtngCtrlSObjectAllProfile.getUIThemeDescription();
    }    
    /*
public static testMethod void testGetContactCategoryOptions_ReturnStringList(){

Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'OS');        
//creating  Custom Settings
List<Global_Settings__c> ls = Test.loadData(Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
//creating  Contacts
TestClassHelper.creatBulkContact(10);


        /**
        *    Checking if there is no Question in the system
        *   
        */
    /*
        System.RunAs(SysAdminUser){
            Test.startTest();
                List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.contSList[0].id, 'Contact');
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.CONTACT_PROFILE_PICKLIST_NONE);
        }
    }
    */
    /*
   public static testMethod void testGetContactCategoryOptions_ReturnStringListWithQuestions(){
       //creating  Questions records
        createQuestions();
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'OS');        
        //creating  Custom Settings
        List<Global_Settings__c> ls = Test.loadData(Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Contacts
        TestClassHelper.creatBulkContact(10);

        
        /**
        *    Checking if there is no Question in the system
        *   
        */
    /*  
    System.RunAs(SysAdminUser){
            Test.startTest();
                List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.contSList[0].id, 'Contact');
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.CONTACT_PROFILE_PICKLIST_NONE);
        }
    }
    */
    /*
    public static testMethod void testGetContactCategoryOptions_returnStringOfCategory_questionswithCategories(){
       //creating  Questions records
        createQuestions();
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'OS');        
        //creating  Custom Settings
        List<Global_Settings__c> ls = Test.loadData(Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Contacts
        TestClassHelper.creatBulkContact(10);
        
        //creating  Contact Profile records
        List<Contact_Profile__c> contproff2 = TestClassHelper.CreateContProfile(TestClassHelper.contSList[2].id,quesList);
        
        
        
        /**
        *    Checking if there is no Question in the system
        *   
        */
        /*
        System.RunAs(SysAdminUser){
            Test.startTest();
                List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.contSList[2].id, 'Contact');
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.CONTACT_PROFILE_PICKLIST_ALL);
            
            List<ContactProfileWrapper> conProfWrp = LtngCtrlSObjectAllProfile.getContactIncrementCounter(TestClassHelper.contSList[2].id,categoryList[0]);
            
            system.assert(conProfWrp.size() > 0);
        }
        
     
    }
    */
    /*
    public static testMethod void testContactSaveResponse_returnString(){
       //creating  Questions records
        createQuestions();
        Profile profSysAdm = [SELECT ID FROM PROFILE WHERE NAME = 'System Administrator'];
        User SysAdminUser = TestClassHelper.CreatUser(profSysAdm.id,'SysAdm', 'OS');        
        //creating  Custom Settings
        List<Global_Settings__c> ls = Test.loadData(Global_Settings__c.sObjectType, 'ApexTestClassDataLoad_Global_Settings');
        //creating  Contacts
        TestClassHelper.creatBulkContact(10);
        
        //creating  Contact Profile records
        List<Contact_Profile__c> contproff2 = TestClassHelper.CreateContProfile(TestClassHelper.contSList[1].id,quesList1);
        
        
        
        /**
        *    Checking  if there is no Question in the system
        *   
        */
        /*
        System.RunAs(SysAdminUser){
            Test.startTest();
                List<String> categoryList = LtngCtrlSObjectAllProfile.getCategoryOptionList(TestClassHelper.contSList[1].id, 'Contact');
            Test.stopTest();
            
            system.assert(categoryList[0] == System.Label.CONTACT_PROFILE_PICKLIST_ALL);
            
            List<ContactProfileWrapper> conProfWrp = LtngCtrlSObjectAllProfile.getContactIncrementCounter(TestClassHelper.contSList[1].id,categoryList[0]);
            
            system.assert(conProfWrp.size() > 0);
        }
    }
    */
    /*
     static testmethod void method1(){
        account acc = new account();
        acc.name= 'nas';
        acc.BST_COUNTRY__c = 'Belgium';
        //acc.RecordType.Name = 'IMS Account';
        acc.BillingStreet = 'test street';
        acc.BillingCity = 'test city';
        acc.BillingPostalCode = '200110';
        acc.BillingCountry = 'test country';
        
        insert acc;
        RestRequest req = new RestRequest();                
        req.params.put('accountID', acc.Id);
        req.params.put('isFilterOnSFGroup', 'True');
        RestResponse res = new RestResponse();    
        RestContext.request = req;
        RestContext.response = res;
        
        AccountProfileQuestions.getQuestionsWithSavedResponses();
        AccountProfileQuestions.getQuesRespGroup(acc.Id,True,true,'HD','Access');
    }*/
}