src/objects/Answer__c.object
<CustomObject>
    <description>Answer records to Question records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Account record.</description>
        <inlineHelpText>Related Account record.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Answer_Statement__c</fullName>
        <description>Answer value.</description>
        <inlineHelpText>Answer value.</inlineHelpText>
        <label>Answer Statement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Related Question record.</description>
        <inlineHelpText>Related Question record.</inlineHelpText>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>Answ-{0000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Record_Types__mdt.object
<CustomObject>
    <description>Record_Types Developer Names.</description>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <description>Developer_Name.</description>
        <inlineHelpText>Developer_Name.</inlineHelpText>
        <label>Developer_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Record_Types</label>
    <pluralLabel>Record_Types</pluralLabel>
</CustomObject>

src/classes/TRY_Lightning_Answer_Controller.cls
public with sharing class TRY_Lightning_Answer_Controller {
@AuraEnabled
    
      public static boolean saveAnswer(Id accountId, Id questionId, string answerValue) {
      
      system.debug('##################################################### YB saveAnswer');    
      
      Answer__c a = new Answer__c();
      a.account__c = accountId;
      a.question__c = questionId;
      a.Answer_Statement__c = answerValue;
      //a.=;
      
      //try{
      
      system.debug('##################################################### YB a ' + a);    
      insert a;
      //}
      
      /*catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
            + e.getMessage());    
        
      }*/
        
      return true;
      } 
      
        
      public static List<Answer__c> getAnswers() {
      
      try{
      /*Record_Types__mdt AccountCompetitorRT_MDT =  [SELECT Id, MasterLabel, Developer_Name__c
                 FROM Record_Types__mdt
                 where MasterLabel = 'Competitor'];
      
      if(AccountCompetitorRT_MDT !=null){    
      system.debug('##################################################### YB AccountCompetitorRT_MDT' + AccountCompetitorRT_MDT);    
      }         
      
      RecordType accountCompetitorRT =  [SELECT Id, Name
                 FROM RecordType
                 where DeveloperName =: AccountCompetitorRT_MDT.Developer_Name__c];
      
      if(accountCompetitorRT !=null){    
      system.debug('##################################################### YB accountCompetitorRT' + accountCompetitorRT);    
      }      */   
                 
      List<Answer__c> answers = 
                [SELECT Id, Name
                 FROM Answer__c];
                 //where RecordTypeId =: accountCompetitorRT.Id];
      
      /*if(competitors !=null){    
      system.debug('##################################################### YB competitors' + competitors);    
      }  */       
                
                 //AND 
                 //ADD SPECIFIC CRITERIA HERE
                
        //Add isAccessible() check
        return answers;
      }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
            + e.getMessage());    
        }
        
    
    } 
}