src/objects/Answer__c.object
<CustomObject>
    <description>Answer records to Question records.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related Account record.</description>
        <inlineHelpText>Related Account record.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Answer_Statement__c</fullName>
        <description>Answer value.</description>
        <inlineHelpText>Answer value.</inlineHelpText>
        <label>Answer Statement</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Related Question record.</description>
        <inlineHelpText>Related Question record.</inlineHelpText>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>Answ-{0000}</displayFormat>
        <label>Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <fields>
        <fullName>BST_PARENT_QUESTION__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>BST - This field is used to lookup to the parent question. the lookup has a filter to retrieve only Active Parent questions where the record type = Global Question (logic done in the lightning component)</description>
        <inlineHelpText>Field used to link a local question to a global/regional or cluster initiative. For example if on global level we need to store the number of beds, this question will be created as Account Question by each country and then linked to the global question</inlineHelpText>
        <label>Parent Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BST_QUESTION_STATEMENT__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This field requires unique value for each record.</inlineHelpText>
        <label>Question Statement</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>BST_STATUS__c</fullName>
        <description>BST - Status of the question. Drive visibility in My Profile/All profile since only active questions are shown on there. Inactive questions can be reported on. Automatic logic based on Start Date/End date to automatically change the status of a question to Active/Inactive based on the current date compared to Start and End Dates</description>
        <inlineHelpText>Status of the question drives visibility in My Profile/All Profile. Only active questions are shown to users for data insert. Inactive questions can be reported on but will not be shown for data gathering</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Record_Types__mdt.object
<CustomObject>
    <description>Record_Types Developer Names.</description>
    <fields>
        <fullName>Developer_Name__c</fullName>
        <description>Developer_Name.</description>
        <inlineHelpText>Developer_Name.</inlineHelpText>
        <label>Developer_Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Record_Types</label>
    <pluralLabel>Record_Types</pluralLabel>
</CustomObject>

src/classes/TRY_Lightning_Questions_Controller.cls
public with sharing class TRY_Lightning_Questions_Controller {
@AuraEnabled
            
      public static List<Question__c> getQuestions() {
        
      try{
        
      Record_Types__mdt CompetitorsQuestionRT_MDT =  [SELECT Id, MasterLabel, Developer_Name__c
                 FROM Record_Types__mdt
                 where MasterLabel = 'Competitor Question'];
      
      if(CompetitorsQuestionRT_MDT !=null){    
      system.debug('##################################################### YB CompetitorsQuestionRT_MDT' + CompetitorsQuestionRT_MDT);    
      }         
      
      RecordType CompetitorQuestionRT =  [SELECT Id, Name
                 FROM RecordType
                 where DeveloperName =: CompetitorsQuestionRT_MDT.Developer_Name__c];
      
      if(CompetitorQuestionRT !=null){    
      system.debug('##################################################### YB CompetitorQuestionRT' + CompetitorQuestionRT);    
      }         
        
      List<Question__c > questions = 
                [SELECT Id, Name, BST_STATUS__c, BST_QUESTION_STATEMENT__c, RecordTypeId, BST_PARENT_QUESTION__c
                 FROM Question__c
                 WHERE RecordTypeId =: CompetitorQuestionRT.Id 
                 AND BST_PARENT_QUESTION__c = null];

      if(questions !=null){    
      system.debug('##################################################### YB questions' + questions);    
      }         
     
        //Add isAccessible() check
        return questions;
        }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
        + e.getMessage());    
        }       
    }
    
      @AuraEnabled
      public static List<Question__c> getSecondQuestion(id parentQuestionId) {
      
      //public static List<Question__c> getSecondQuestion() {
       
      system.debug('##################################################### YB getSecondQuestion !');    
        
      try{
        
      List<Question__c> questions = new List<Question__c>();
      
      Record_Types__mdt CompetitorsQuestionRT_MDT =  [SELECT Id, MasterLabel, Developer_Name__c
                 FROM Record_Types__mdt
                 where MasterLabel = 'Competitor Question'];
      
      if(CompetitorsQuestionRT_MDT !=null){    
      system.debug('##################################################### YB CompetitorsQuestionRT_MDT' + CompetitorsQuestionRT_MDT);    
      }         
      
      RecordType CompetitorQuestionRT =  [SELECT Id, Name
                 FROM RecordType
                 where DeveloperName =: CompetitorsQuestionRT_MDT.Developer_Name__c];
      
      if(CompetitorQuestionRT !=null){    
      system.debug('##################################################### YB CompetitorQuestionRT' + CompetitorQuestionRT);    
      }         
      
      if(parentQuestionId != null){
      questions = 
                [SELECT Id, Name, BST_STATUS__c, BST_QUESTION_STATEMENT__c, RecordTypeId, BST_PARENT_QUESTION__c
                 FROM Question__c
                 WHERE RecordTypeId =: CompetitorQuestionRT.Id 
                 AND BST_PARENT_QUESTION__c =: parentQuestionId];
      }

      if(questions !=null){    
      system.debug('##################################################### YB questions' + questions);    
      }         
     
      //Add isAccessible() check
      return questions;
      }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
        + e.getMessage());    
        }       
    }
    
    /*public static boolean saveAnswer(Id accountId, Id questionId, string answerValue) {
      
    boolean result = TRY_Lightning_Answer_Controller.saveAnswer(accountId, questionId, answerValue);
    return result;
    
    }*/
    
    @AuraEnabled
    public static boolean saveAnswer(Id accountId, Id questionId, string answerValue) {
      
      system.debug('##################################################### YB saveAnswer');    
      
      Answer__c a = new Answer__c();
      a.account__c = accountId;
      a.question__c = questionId;
      a.Answer_Statement__c = answerValue;
      //a.=;
      
      try{
      system.debug('##################################################### YB a ' + a);    
      insert a;
      }
      
      catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
            + e.getMessage());    
        
      }
        
      return true;
      } 
    
}