src/objects/BXGO_Competitor_Product__c.object
<CustomObject>
    <description>Product that is sold by a Competitor.</description>
    <fields>
        <fullName>BXGO_Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only select Accounts with a &apos;Competitor&apos; Record Type.</errorMessage>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>BST_Competitor</value>
            </filterItems>
            <infoMessage>Please select an Account with a &apos;Competitor&apos; Record Type.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Competitor Products</relationshipLabel>
        <relationshipName>Competitor_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BXGO_List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Competitor Product</label>
    <nameField>
        <label>Competitor Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Competitor Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TRY_Lightning_Products_Controller.cls
public with sharing class TRY_Lightning_Products_Controller {

@AuraEnabled
public static List<BXGO_Competitor_Product__c> getProducts(id accountId) {
        
        try{
        
        List<BXGO_Competitor_Product__c> products = new List<BXGO_Competitor_Product__c>();
        
        if(accountId!=null)
            {
        system.debug('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ YB compS list -> comp accountId : ' + accountId);
        
        products = [SELECT Id, Name, BXGO_Competitor__c, BXGO_List_Price__c, Count__c  
                    FROM BXGO_Competitor_Product__c
                    WHERE BXGO_Competitor__c =: accountId];

        //Add isAccessible() check
        system.debug('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ YB compS list -> comp products : ' + products);
        }
        
             else {
             system.debug('++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ YB WARNING : Class TRY_Lightning_Products_Controller: accountId is null!');
             }    

        return products;
        }
        
        catch (Exception e) {
        // "Convert" the exception into an AuraHandledException
        throw new AuraHandledException('Something went wrong: '
        + e.getMessage());    
        }
              
    }
    
}