src/objects/INTEGRATION_LOG__c.object
<CustomObject>
    <description>Custom object used for IMS approval process for objects Account, Contact, AccountContactRelationShip, Account_Account_Relation__c</description>
    <fields>
        <fullName>BST_CONTACT_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Id to track changes made for the Contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>IMS Integration Logs</relationshipLabel>
        <relationshipName>IMS_Integration_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>IMS Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000}</displayFormat>
        <label>BOOST Integration Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IMS Integration Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TgrIMSContactFieldAuditTrigger_Test.cls
//Akshay 11/23/2016
//Description - This class will be used for test coverage of TgrIMSContactFieldAuditTrigger trigger on contact

@isTest
public class TgrIMSContactFieldAuditTrigger_Test{
    
    static testMethod void testContactInsert(){
        test.startTest();
        Contact con = ClsTestDataUtility.createContact();
        insert con;
        test.StopTest();
    }  
 
    static testMethod void testContactUpdate(){
        test.startTest();
        Contact con = ClsTestDataUtility.createContact();
        insert con;
        con.firstName = 'Test Test First';
        update con;
        test.stopTest();
    }
    
    static testMethod void testContactNonAdminInsert(){
        test.startTest();
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u){
            Contact con = ClsTestDataUtility.createContact(); 
            insert con;
            //List<INTEGRATION_LOG__c> iList = [select id, name,BST_CONTACT_ID__c from INTEGRATION_LOG__c WHERE BST_CONTACT_ID__c =:con.id ];
            //system.assertEquals(con.Id,iList[0].BST_CONTACT_ID__c,'Error');
            test.stopTest();
       }
   }
   
   static testMethod void testContactNonAdminUpdate(){
        test.startTest();
        user u = ClsTestDataUtility.createUser('Belgium','Belgium');
        System.runAs(u){
            Contact con = ClsTestDataUtility.createContact(); 
            insert con;
            con.firstName = 'Test Test First';
            update con;
            system.AssertEquals('Test Test First',con.FirstName,'Error');
            test.stopTest();
       }
   }   
}