src/objects/Question__c.object
<CustomObject>
    <description>Object used to store the Question for 

1. Account Profile 
2. Contact Profile
3. Global or Regional Parent Questions for Account Profile and Contact Profile</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Ques-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>BST_SECONDARY_COUNTRY__c</fullName>
        <description>Field to track the secondary country of the User.</description>
        <label>Secondary Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>France</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Netherlands</fullName>
                </value>
                <value>
                    <fullName>Canada</fullName>
                </value>
                <value>
                    <fullName>Turkey</fullName>
                </value>
                <value>
                    <fullName>Dom Com</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                    <isActive>false</isActive>
                    <label>Andorra</label>
                </value>
                <value>
                    <fullName>Global</fullName>
                    <isActive>false</isActive>
                    <label>Global</label>
                </value>
                <value>
                    <fullName>Luxembourg</fullName>
                    <isActive>false</isActive>
                    <label>Luxembourg</label>
                </value>
                <value>
                    <fullName>Monaco</fullName>
                    <isActive>false</isActive>
                    <label>Monaco</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClsQuestionLightningController_Test.cls
/********************************************************************************
Apex Class Name - ClsQuestionLightningController_Test
Version - 1.0
Created Date- 12-June-2017 by - Shashank 
Function - This class will be used for test coverage of ClsQuestionLightningController.
********************************************************************************/

@isTest
public class ClsQuestionLightningController_Test{

        Static testMethod void testClsApexUtil1()
        {
            test.startTest();
            
                Question__c ques= ClsTestDataUtility.createGlobalQuestion();
                insert ques;
                user u = ClsTestDataUtility.createUser('Belgium','Belgium');
                System.runAs(u){ 
                Question__c ques1= ClsTestDataUtility.createLocalQuestion();
                insert ques1;
                }
                
                ClsQuestionLightningController.getRecordTypeId('Question__c','Global Question');
                ClsQuestionLightningController.getRecordTypeId('Question__c','Account Profile Question');
                ClsQuestionLightningController.getUserInfo();
                ClsQuestionLightningController.getQuestionRecordTypes();
                ClsQuestionLightningController.getCountryValues();
                
                ClsQuestionLightningController.getMajorCategory(u.BST_SECONDARY_COUNTRY__c);
                ClsQuestionLightningController.getCategory('Renal');
                
                ClsQuestionLightningController.getQuestionType();
                ClsQuestionLightningController.getResponseType();
                ClsQuestionLightningController.getSalesforceGroup(u.BST_SECONDARY_COUNTRY__c);
                ClsQuestionLightningController.getSalesProcess();
                ClsQuestionLightningController.getStatus();
                ClsQuestionLightningController.getProfileType();
                ClsQuestionLightningController.saveQuestion(ques);
                ClsQuestionLightningController.getQuestionDetails(ques.Id);
                ClsQuestionLightningController.getUserCountry();
                ClsQuestionLightningController.getHelptextMap();
            test.stopTest();
        
        }
        
        
        
}