src/objects/Survey_Response__c.object
<CustomObject>
    <description>Survey Response received from contacts</description>
    <fields>
        <fullName>Question_Identifier__c</fullName>
        <description>Unique question identifier</description>
        <label>Question Identifier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Target__c</fullName>
        <description>Survey Target</description>
        <inlineHelpText>Survey Target - Master</inlineHelpText>
        <label>Survey Target</label>
        <referenceTo>Survey_Target__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text_Value__c</fullName>
        <description>Text Value</description>
        <inlineHelpText>Text Value</inlineHelpText>
        <label>Text Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Survey_Target__c.object
<CustomObject>
    <description>To store surveys initiated by Reps</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to survey</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Targets</relationshipLabel>
        <relationshipName>Survey_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact related survey</description>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>Please choose a contact with Email address.</errorMessage>
            <filterItems>
                <field>Contact.Email</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Survey Targets</relationshipLabel>
        <relationshipName>Survey_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detractor__c</fullName>
        <description>Set 1 if NPS Value &lt;= 6</description>
        <formula>IF ((NOT(ISBLANK(NPS_Value__c))) &amp;&amp;  ISPICKVAL(Status__c,&apos;Completed&apos;) &amp;&amp; NPS_Value__c &lt;=6,1,NULL)</formula>
        <label>Detractor</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NPS_Value__c</fullName>
        <description>Response value of question that contributes to Net Promoter Score in the survey</description>
        <inlineHelpText>Response value of question that contributes to Net Promoter Score in the survey</inlineHelpText>
        <label>NPS Value</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Completed_Date__c</fullName>
        <description>Survey Completed Date</description>
        <inlineHelpText>Survey Completed Date</inlineHelpText>
        <label>Survey Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey_Sent_Date__c</fullName>
        <description>Survey Sent Date</description>
        <label>Survey Sent Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Territory_Business_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Territory Business Manager associated with Survey</description>
        <label>Territory Business Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Survey Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/surveyDetails.cls
public class surveyDetails {
    
    public Id surveyTargetId{get; set;}    
    public Survey_Target__c surveyTarget;
    public Survey_Response__c surveyResponceReason;
    public Survey_Response__c surveyResponceImprovement;
	public map<string, string> responses{get; set;}
     
    
    public Survey_Target__c getSurvey()
    {       
        surveyTarget = [SELECT Id,Account__r.Name,Contact__r.Name,Contact__r.Phone,Detractor__c,NPS_Value__c,Survey_Completed_Date__c,Survey_Sent_Date__c ,
                        Territory_Business_Manager__r.Name
                          FROM Survey_Target__c
                         WHERE Id = :surveyTargetId];
        return surveyTarget;
    }
    
    public Survey_Response__c getReason()
    {
        
        surveyResponceReason = [SELECT Id,Question_Identifier__c,Text_Value__c 
                            FROM Survey_Response__c
                           WHERE Survey_Target__c = :surveyTargetId and Question_Identifier__c = 'Score Reason'];
        
        
        /*if(surveyResponce.size() > 0){
            for(Survey_Response__c responce:surveyResponce){
                responces.put(responce.Question_Identifier__c, responce.Text_Value__c) ;
            }
        }
        system.debug('responces' +responces);*/
        //reason = responces.get('Score Reason');
        //improvement = responces.get('Better Partner');
        return surveyResponceReason;
    }
    
    public Survey_Response__c getImprovement()
    {
        system.debug('surveyTargetId' +surveyTargetId);
        surveyResponceImprovement = [SELECT Id,Question_Identifier__c,Text_Value__c 
                            FROM Survey_Response__c
                           WHERE Survey_Target__c = :surveyTargetId and Question_Identifier__c = 'Better Partner'];
        
        
        return surveyResponceImprovement;
    }
    
    public map<string,string> getresponseMap(){
        
        list<Survey_Response__c> surveyResponse = [SELECT Id,Question_Identifier__c,Text_Value__c 
                            FROM Survey_Response__c
                           WHERE Survey_Target__c = :surveyTargetId ];
        responses.put('T1', 'T2') ;
        /*if(surveyResponse.size() > 0){
            for(Survey_Response__c response:surveyResponse){
                responses.put(response.Question_Identifier__c, response.Text_Value__c) ;
            }
        }*/
        return responses;
    }
    
    

}