src/objects/Survey_Target__c.object
<CustomObject>
    <description>To store surveys initiated by Reps</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to survey</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Survey Targets</relationshipLabel>
        <relationshipName>Survey_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Vice_President__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Area Vice President for the Survey</description>
        <label>Area Vice President</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Targets_AVP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Any comments that RBM or AVP wants to capture</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <description>Email of address of contact used for survey emailing</description>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opt Out identifier. Checked means opted out.</description>
        <label>Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recipient_Id__c</fullName>
        <description>Recipient ID of third party survey system</description>
        <label>Recipient Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Regional_Business_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Regional Business Manager</description>
        <label>Regional Business Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Target_RBM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Root_Cause__c</fullName>
        <description>To capture root cause in case of detractor</description>
        <label>Root Cause</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Contracts/Compliance</fullName>
                </value>
                <value>
                    <fullName>Pricing</fullName>
                </value>
                <value>
                    <fullName>Quality</fullName>
                </value>
                <value>
                    <fullName>Sales Representative</fullName>
                </value>
                <value>
                    <fullName>Supply</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Group__c</fullName>
        <description>Sales Group Survey belongs to</description>
        <inlineHelpText>Sales Group Survey belongs to</inlineHelpText>
        <label>Sales Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Survey status</description>
        <inlineHelpText>Survey Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>NoResponse</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Pilot</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Business_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Territory Business Manager associated with Survey</description>
        <label>Territory Business Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Targets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Up_Level1__c</fullName>
        <description>Region Code</description>
        <inlineHelpText>Region Code</inlineHelpText>
        <label>Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Up_Level2__c</fullName>
        <description>Area Code</description>
        <inlineHelpText>Area Code</inlineHelpText>
        <label>Area</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <description>Territory code</description>
        <inlineHelpText>Territory Code</inlineHelpText>
        <label>Territory</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Survey Target</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Survey Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SurveyTargetTriggerHandler.cls
/********************************************************************************
Apex Class Name - SurveyTargetTriggerHandler 
Version - 1.0
Created Date - July 21, 2017
Description - Trigger Handler class for Survey Target.

Modification Log : 
--------------------------------------------------------------------------------

* Developer               Date                 Description
* -------------------     ------------         -----------------------
* Cognizant Developer     07/21/2017           Original Version
********************************************************************************/
public class SurveyTargetTriggerHandler {
    
    /*
     * Handle beforeUpdate trigger event
    */       
    public static void handleBeforeUpdate(list<Survey_Target__c> newSurveyTarget, list<Survey_Target__c> oldSurveyTarget, 
    										map<Id, Survey_Target__c> newMap, map<Id, Survey_Target__c> oldMap)
    {
    	map<Id,Survey_Target__c> completedSurvey = new map<Id,Survey_Target__c>();
    	map<Id,String> surveyAccountMap = new map<Id,String>();
    	map<Id, TerritoryHierarchy> surveyHierarchyMap = new Map<Id, TerritoryHierarchy>();
    	map<Id, Id> surveyTerritoryMap = new Map<Id, Id>();
    	
    	set<Id> accountList = new set<Id>();
     	for(Survey_Target__c survey : newSurveyTarget){
    		if(survey.status__c == 'Completed' && oldMap.get(survey.Id).status__c != survey.status__c){
    			completedSurvey.put(survey.Id, survey);
    			surveyAccountMap.put(survey.Id,survey.account__c + '~' + survey.sales_group__c);
    			accountList.add(survey.account__c);
    		}
    	}
    	if(completedSurvey.size() > 0){
    		surveyHierarchyMap = TerritoryHierarchyHelper.getAccountHierarchy(accountList, surveyAccountMap);
    		for(Survey_Target__c survey : newSurveyTarget){
    			if(surveyHierarchyMap.get(survey.Id) != NULL && surveyHierarchyMap.get(survey.Id).TBMcode!= NULL){
		    		survey.Territory__c  = surveyHierarchyMap.get(survey.Id).TBMcode;
					survey.Territory_Up_Level1__c = surveyHierarchyMap.get(survey.Id).RBMcode;
					survey.Territory_Up_Level2__c = surveyHierarchyMap.get(survey.Id).AVPcode;
					survey.Territory_Business_Manager__c = (surveyHierarchyMap.get(survey.Id).TBMuser != NULL?surveyHierarchyMap.get(survey.Id).TBMuser:NULL);
					survey.Regional_Business_Manager__c = (surveyHierarchyMap.get(survey.Id).RBMuser != NULL?surveyHierarchyMap.get(survey.Id).RBMuser:NULL);
					survey.Area_Vice_President__c = (surveyHierarchyMap.get(survey.Id).AVPuser != NULL?surveyHierarchyMap.get(survey.Id).AVPuser:NULL);
					//optout handling
					if(survey.Opt_Out__c && survey.recipient_id__c != NULL){
						survey.recipient_id__c = survey.recipient_id__c.substring(survey.recipient_id__c.IndexOf('MLRP'));
					}
					surveyTerritoryMap.put(survey.Id, surveyHierarchyMap.get(survey.Id).TBMID);
	    		}
    		}
    		if(surveyTerritoryMap.size() > 0)
				SurveyTargetHelper.shareSurveyTBMTerritory(surveyTerritoryMap);
    	}
    } 
    
    /*
     * Handle afterInsert trigger event
    */    
    public static void handleAfterInsert(list<Survey_Target__c> newSurveyTarget)
    {
          
    }

    /*
     * Handle afterUpdate trigger event
    */    
    public static void handleAfterUpdate(map<Id, Survey_Target__c> newMap, map<Id, Survey_Target__c> oldMap)
    {
    	list<Id> stTaskClose = new list<Id>(); 
    	list<Id> stTaskUpdate = new list<Id>();    
    	map<String,String> optOutList = new map<String,String>(); 	
     	for(Survey_Target__c survey : newMap.values()){
    		if(survey.status__c == 'Completed'){
	    		if(String.isBlank(oldMap.get(survey.Id).root_cause__c) && String.isNotBlank(newMap.get(survey.Id).root_cause__c)){
	    			stTaskClose.add(survey.id);
	    		}
	    		else if(String.isBlank(oldMap.get(survey.Id).comments__c) && String.isNotBlank(newMap.get(survey.Id).comments__c)){
	    			stTaskUpdate.add(survey.id);
	    		}
	    		
	    		if(survey.Opt_Out__c && survey.recipient_id__c != NULL && oldMap.get(survey.Id).recipient_id__c == NULL){
	    			optOutList.put(survey.recipient_id__c, survey.contact_email__c);
	    		}
    		}

    	}
    	if(stTaskClose.size() > 0)
    		SurveyTargetHelper.closeDetractorTask(stTaskClose);	 
    	if(stTaskUpdate.size() > 0)
    		SurveyTargetHelper.updateDetractorTaskStatus(stTaskUpdate);	   
    	/*if(optOutList.size() > 0)
    		SurveyTargetHelper.optoutInQualtrics(optOutList);
    	*/	    
    }
}